#!/bin/sh -eux

rm CMakeLists.txt

ub_compile \
	--enable-libffi \
	--disable-expensive-checks \
	--disable-debug-runtime \
	--disable-assertions \
	--enable-optimized \
	--enable-experimental-targets=R600

#	-DLLVM_ENABLE_PIC:BOOL=OFF \
#	-DLLVM_ENABLE_ASSERTIONS:BOOL=OFF
