#!/bin/sh -eux

ub_install

mkdir -p "$UB_INSTALLDIR/usr/share/doc/clang/html"
cp -r docs/_build/html/* "$UB_INSTALLDIR/usr/share/doc/clang/html/"
rm -r "$UB_INSTALLDIR/usr/share/doc/clang/html/_sources"
