#!/bin/sh -eux

DESTDIR="$UB_INSTALLDIR"
BINDIR="$DESTDIR"/usr/bin
DATADIR="$DESTDIR"/usr/share/ep128
PIXMAPDIR="$DESTDIR"/usr/share/pixmaps
DESKTOPDIR="$DESTDIR"/usr/share/applications

#célkönyvtárak
mkdir -p "$BINDIR" "$PIXMAPDIR" "$DESKTOPDIR" "$DATADIR"/{roms,disk,config}

mv ep128emu_roms.bin roms/
cp -r roms config disk "$DATADIR"/
cp resource/*.desktop "$DESKTOPDIR"/
cp ep128emu tapeedit resource/{zx128emu,cpc464emu} "$BINDIR"/

#ico fájlok konverziója
convert resource/ep128emu.ico $PIXMAPDIR/ep128emu.png
convert resource/zx128emu.ico $PIXMAPDIR/zx128emu.png
convert resource/cpc464em.ico $PIXMAPDIR/cpc464emu.png
convert resource/tapeedit.ico $PIXMAPDIR/tapeedit.png

#makecfg wrapper célja
mv makecfg "$DATADIR"/makecfg.bin
