#!/bin/sh -eux

celdir="$UB_INSTALLDIR"/usr/share/ep128/
install -d -m 0775 "$celdir"/{roms,disk,config}
cp ep128emu  tapeedit "$UB_INSTALLDIR"/usr/bin
cp -r roms config disk "$celdir"/
cp makecfg "$celdir"/makecfg.bin
