#!/bin/sh -eux

cp -a emoc "$UB_INSTALLDIR"/usr/bin/
cp -a emoc-48.png "$UB_INSTALLDIR"/usr/share/pixmaps/emoc.png
cp -a emoc.desktop "$UB_INSTALLDIR"/usr/share/applications/
mkdir -p "$UB_INSTALLDIR"/usr/share/doc/emoc/
cp -a documentation/emoc_hlp.html "$UB_INSTALLDIR"/usr/share/doc/emoc/
