#!/bin/sh -eux

ub_compile \
	--enable-cups \
	--with-drivers=ALL \
	--with-ijs \
	--with-fontpath="/usr/share/fonts/ghostscript:/usr/share/fonts/Type1:/usr/share/fonts/TTF" \
	--with-system-libtiff

cd ijs
autoreconf -ivf
ub_compile
