#!/bin/sh -eux

autoreconf -vif
ub_compile \
	--enable-multibyte \
	--enable-nls \
	--enable-iconv \
	--disable-gtk \
	--enable-perllib \
	--enable-rsvg \
	--enable-xft \
	--enable-bidi \
	--with-stroke-library

