#!/bin/sh -eux

mv ${UHUBUILD_WORKDIR}/compile/cfe-${UB_VERSION}.src tools/clang
mv ${UHUBUILD_WORKDIR}/compile/clang-tools-extra-${UB_VERSION_HEAD2} tools/clang-tools-extra
mv ${UHUBUILD_WORKDIR}/compile/compiler-rt-${UB_VERSION_HEAD2} projects/compiler-rt

ub_compile \
	-DLLVM_ENABLE_PIC:BOOL=OFF \
	-DLLVM_ENABLE_ASSERTIONS:BOOL=OFF \
	--libdir=/usr/lib/llvm \
	--sysconfdir=/etc \
	--enable-shared \
	--enable-libffi \
	--enable-targets=all \
	--disable-expensive-checks \
	--disable-debug-runtime \
	--disable-assertions \
	--with-binutils-include=/usr/include \
	--enable-optimized

make -C docs -f Makefile.sphinx man
make -C docs -f Makefile.sphinx html
make -C tools/clang/docs -f Makefile.sphinx html
