#!/bin/sh -eux

ub_install

DST="$UB_INSTALLDIR/usr"
rm -f "$DST"/bin/ll*
rm -f "$DST"/bin/bugpoint
rm -f "$DST"/bin/macho-dump
rm -f "$DST"/bin/opt
rm -fr "$DST"/include/llvm
rm -fr "$DST"/include/llvm-c
rm -fr "$DST"/lib/ocaml
rm -f "$DST"/lib/BugpointPasses.so
rm -f "$DST"/lib/LLVMHello.so
rm -fr "$DST"/lib/bfd-plugins
rm -f "$DST"/lib/libLLVM*.*
rm -f "$DST"/lib/libLTO.*
rm -f "$DST"/lib/libllvm*.*
rm -f "$DST"/lib/libprofile_rt.*
rm -fr "$DST"/share/doc/llvm

mkdir -p "$DST/share/doc/clang/html"
cp -r docs/_build/html/* "$DST/share/doc/clang/html/"
rm -r "$DST/share/doc/clang/html/_sources"
