#!/bin/sh -eux

# deprecated in 5.5: Qt WebKit, Qt Declarative (Qt Quick 1), Qt Script

# qtwebengine: külön csomag

export LD_LIBRARY_PATH="$(pwd)"/lib

./configure \
	-platform linux-g++-32 \
	-prefix /usr/lib/qt5 \
	-sysconfdir /etc/xdg \
	\
	-release            \
	-opensource         \
	-confirm-license	\
	-shared             \
	-largefile          \
	-c++11              \
	-rpath              \
	-verbose            \
	-silent             \
	-optimized-qmake    \
	-reduce-exports		\
	-no-qml-debug       \
	-no-journald		\
	-no-separate-debug-info \
	\
	-nomake examples    \
	-nomake tests		\
	-skip qtwebengine	\
	\
	-accessibility      \
	\
	-plugin-sql-mysql -I/usr/include/mysql \
	-plugin-sql-psql -I/usr/include/postgresql -I/usr/include/postgresql/server \
	-plugin-sql-odbc    \
	-plugin-sql-sqlite  \
	\
	-audio-backend      \
	-gstreamer 1.0		\
	\
	-system-freetype	\
	-system-harfbuzz	\
	-system-libjpeg     \
	-system-libpng      \
	-system-pcre		\
	-system-sqlite		\
	-system-zlib        \
	-system-xcb         \
	-system-xkbcommon-x11 \
	\
	-openssl-linked     \
	\
	-no-nis             \
	-cups               \
	-iconv              \
	-no-pch             \
	-dbus-linked        \
	-mtdev				\
	\
	-glib               \
	-gtkstyle           \
	-opengl             \
	-no-linuxfb         \
	-no-openvg          \
	-no-eglfs           \
	-no-kms             \
	\
	-sm                 \
	-xshape             \
	-xsync              \
	-xinerama           \
	-xcursor            \
	-xfixes             \
	-xrandr             \
	-xrender            \
	-mitshm             \
	-fontconfig         \
	-xinput             \
	-xkb                \
	\
	-lcrypto            \
	-lcrypt             \
	-lssl               \

ub_make

#some options we may want to use in the future
#	-nomake tests       \

