#!/bin/sh -eux

if [ "$UB_ARCH" == "amd64" ];then
ub_replace -O3 -O2 configure
ub_replace -O3 -O2 configure.in
ub_replace -O3 -O2 ext/fiddle/libffi-3.2.1/m4/ax_cc_maxopt.m4
ub_replace -O3 -O2 ext/fiddle/libffi-3.2.1/configure
fi
ub_compile \
	--with-dbm-type=gdbm_compat
