#!/bin/sh -eux

ub_install

for i in images/logo/bittorrent_*.png; do
	size="${i#*_}"
	size="${size%.png}"
	install -D -m 644 "$i" "$UB_INSTALLDIR/usr/share/icons/hicolor/${size}x${size}/apps/bittorrent.png"
done
