#!/bin/sh -eux

sed -i -e '1{
  i#! /usr/bin/tcc -run
  /^#!/d
}' examples/ex*.c
sed -i -e '1s/$/ -lX11/' examples/ex4.c
    
./configure --prefix=/usr
make

make CFLAGS="-fPIC" libtcc.o
ld -shared -soname libtcc.so -o libtcc.so libtcc.o
