#!/bin/sh -eux

./configure

make \
    tccdir="$UB_INSTALLDIR"/usr/lib/tcc \
    libdir="$UB_INSTALLDIR"/usr/lib \
    mandir="$UB_INSTALLDIR"/usr/share/man bindir="$UB_INSTALLDIR"/usr/bin \
    includedir="$UB_INSTALLDIR"/usr/include \
    docdir="$UB_INSTALLDIR"/usr/share/doc/tcc \
    infodir="$UB_INSTALLDIR"/usr/share/info \
    install
make clean
make CFLAGS="-fPIC"
ld -shared -soname libtcc.so -o libtcc.so *.o
install -D -m 755 libtcc.so "$UB_INSTALLDIR"/usr/lib/libtcc.so
mkdir -p "$UB_INSTALLDIR"/usr/share/doc/tcc/examples
cp -p examples/*.c "$UB_INSTALLDIR"/usr/share/doc/tcc/examples/
