#!/bin/sh -eux

if [ $((`stat -f -c "%a" .`*`stat -f -c "%s" .`/(1024*1024*1024))) -lt 12 ]; then
	echo "At least 12 GB free space is required!"
	exit 1
fi

ccache --max-size=12G

# átpakolunk az /src alá mindent, mert
# ott fogja keresni a letöltött forráscsomagokat
if [ ! -d src ]; then
mkdir src
fi
mv *.{gz,zip,bz2,tgz} src/

# ha van a distro-configs alatt megfelelő tartalmú .conf fájl, ekkor az
# ./autogen.sh --with-distro=<conffile> is használható
# a LibreOfficeUHU.conf fájlhoz
# ./autogen.sh --with-distro=LibreOfficeUHU
# egyébként az autogen.input a preferált (ebben felsorolni az opciókat),
# csak ne legyenek idézőjelek az opciókban (pl. --prefix="/usr"), attól kiakad!

export QT4DIR=/usr/lib/qt4

# opciók a distro-configs/LibreOfficeUHU.conf-ból
./autogen.sh \
	--with-distro=LibreOfficeUHU

# --disable-gnome-vfs van...
sed -i 's/uses_gnomevfs=true/uses_gnomevfs=false/g' sysui/desktop/mimetypes/openoffice.applications

# az unitcheck és a slowcheck nem kell
make build-nocheck

