#!/bin/sh -eux

if [ "$UB_ARCH" == "amd64" ];then
mode="64"
else
mode="32"
fi
CC="ccache gcc -m${mode}"
CXX="ccache g++ -m${mode}"

export LDFLAGS="-Wl,-rpath,/usr/lib/seamonkey/ -Wl,--no-keep-memory -Wl,-z,relro -Wl,-z,now"
export CFLAGS=" -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
export CXXFLAGS=" -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
# jpeg: jpeg-turbo, png: >= 1.6.17 + APNG support

: > .mozconfig
cat > .mozconfig << _EOF_
ac_add_options --host='i686-gnu-linux'
ac_add_options --target='i686-gnu-linux'
ac_add_options --prefix=/usr
ac_add_options --enable-application=suite
ac_add_options --enable-release
ac_add_options --enable-official-branding
ac_add_options --enable-optimize="-O2"
ac_add_options --with-pthreads
ac_add_options --with-system-bz2
ac_add_options --with-system-icu
ac_add_options --with-system-libevent
ac_add_options --with-system-libvpx
ac_add_options --with-system-nss
ac_add_options --with-system-nspr
ac_add_options --with-system-zlib
ac_add_options --with-system-jpeg
ac_add_options --with-system-png
ac_add_options --enable-system-cairo
ac_add_options --enable-system-hunspell
ac_add_options --enable-system-sqlite
ac_add_options --enable-gio
ac_add_options --enable-startup-notification
ac_add_options --enable-default-toolkit=cairo-gtk2
ac_add_options --enable-necko-wifi
ac_add_options --enable-safe-browsing
ac_add_options --enable-url-classifier
ac_add_options --disable-clang-plugin
ac_add_options --disable-crashreporter
ac_add_options --disable-stylo
ac_add_options --disable-debug
ac_add_options --disable-gconf
ac_add_options --disable-gnomeui
ac_add_options --disable-updater
ac_add_options --disable-tests
ac_add_options --disable-strip
ac_add_options --disable-install-strip
ac_add_options --disable-elf-hack
_EOF_

if [ "$UB_ARCH" == "amd64" ];then
sed -i 's/i686-gnu-linux/x86_64-gnu-linux/' .mozconfig
fi

cd "$UB_OBJECTDIR"

# az UB_CONFIGURE_DIR="$UB_COMPILEDIR" forma nem jó, linker hiba lesz belőle
"$UB_COMPILEDIR"/configure

ub_make
