#!/bin/sh -eux

cd "$UB_OBJECTDIR"
ub_install

rm -f "$UB_INSTALLDIR"/usr/lib/seamonkey/seamonkey
rm -f "$UB_INSTALLDIR"/usr/bin/seamonkey
ln -s /usr/lib/seamonkey/seamonkey "$UB_INSTALLDIR"/usr/bin/seamonkey

ln -s seamonkey "$UB_INSTALLDIR"/usr/lib/seamonkey-"$UB_VERSION"
ln -s seamonkey-devel "$UB_INSTALLDIR"/usr/lib/seamonkey-devel-"$UB_VERSION"
ln -s seamonkey-"$UB_VERSION" "$UB_INSTALLDIR"/usr/include/seamonkey
ln -s seamonkey-"$UB_VERSION" "$UB_INSTALLDIR"/usr/share/idl/seamonkey

cp "$UB_INSTALLDIR"/usr/lib/seamonkey/chrome/icons/default/default48.png "$UB_INSTALLDIR"/usr/share/pixmaps/seamonkey.png

mkdir -p "$UB_INSTALLDIR"/usr/lib/seamonkey/extensions/langpack-hu@seamonkey.mozilla.org
cp -aR "$UB_COMPILEDIR"/langpack-hu/. "$UB_INSTALLDIR"/usr/lib/seamonkey/extensions/langpack-hu@seamonkey.mozilla.org/
