#!/bin/bash

if [ $# != 1 ]; then
	echo "Usage: $0 filenametemplate" >&2
	exit 1
fi

lang=""
if [ -n "$LC_ALL" ]; then
	lang="$LC_ALL"
elif [ -n "$LC_MESSAGES" ]; then
	lang="$LC_MESSAGES"
elif [ -n "$LANG" ]; then
	lang="$LANG"
fi

lang="${lang%%[.@]*}"
if [ -r "$1.$lang" ]; then
	exec cat "$1.$lang"
fi

lang="${lang%%_*}"
if [ -r "$1.$lang" ]; then
	exec cat "$1.$lang"
fi

if [ -r "$1" ]; then
	exec cat "$1"
fi
