#!/bin/sh -eux

python2 pypy/tool/release/package.py --archive-name pypy --targetdir .

mkdir unpacked
tar xf pypy.tar.bz2 -C unpacked

mkdir -p "$UB_INSTALLDIR"/usr/lib/pypy/bin

cd unpacked
install -Dm755 pypy/bin/pypy "$UB_INSTALLDIR"/usr/lib/pypy/bin/pypy
install -Dm755 pypy/bin/libpypy-c.so "$UB_INSTALLDIR"/usr/lib/libpypy-c.so
cp -r pypy/include pypy/lib_pypy pypy/lib-python pypy/site-packages "$UB_INSTALLDIR"/usr/lib/pypy/
cd ..

mkdir -p "$UB_INSTALLDIR"/usr/bin
ln -s /usr/lib/pypy/bin/pypy "$UB_INSTALLDIR"/usr/bin/pypy

