#!/bin/sh -eux

ub_compile \
	--with-openldap=yes \
	--with-krb5=/usr \
	--enable-vala-bindings \
	--disable-uoa \
	--without-phonenumber \
	--disable-google-auth \
	--disable-examples \
	--enable-smime
