#!/bin/sh -eux

make \
	USEPAK="1" \
	BINDIR="$UB_INSTALLDIR/bin/" \
	DATADIR="$UB_INSTALLDIR/usr/share/games/blobwars/" \
	DOCDIR="$UB_INSTALLDIR/usr/share/doc/blobwars/html/" \
	ICONDIR="$UB_INSTALLDIR/usr/share/icons/hicolor/" \
	DESKTOPDIR="$UB_INSTALLDIR/usr/share/applications/" \
	LOCALEDIR="$UB_INSTALLDIR/usr/share/locale/" \
	install
