#!/bin/sh -eux

cd "$UB_OBJECTDIR"

UB_CONFIGURE_DIR="$UB_COMPILEDIR" \
LIBS="-lpthread" \
ub_configure \
	--bindir=/bin \
	--libdir=/lib \
	--sbindir=/sbin \
	--enable-dynamic-e2fsck \
	--enable-elf-shlibs \
	--disable-libblkid \
	--disable-uuidd \
	--disable-libuuid \
	--disable-fsck

ub_make
