#!/bin/sh -eux

meson build \
	--prefix="/usr"             \
	--sysconfdir="/etc"         \
	--localstatedir="/var"      \
	--mandir="/usr/share/man"   \
	--infodir="/usr/share/info" \
	--backend=ninja		        \
	--buildtype=release         \
	--default-library=shared \
	--libdir="/usr/lib"
