#!/bin/sh -eux

cp acpidump/acpidump acpixtract/acpixtract madt/madt "$UB_INSTALLDIR"/sbin/
cp turbostat/turbostat "$UB_INSTALLDIR"/usr/bin/
cp turbostat/turbostat.8 "$UB_INSTALLDIR"/usr/share/man/man8/
