#!/bin/bash
#vdr és xbmc indító szkript xbmc felülethez
# szükséges pluginok
VDRPLUGINS=" -\"Psc\" \
	-\"Pxvdr\"
  "
VDRPRG="/usr/bin/vdr"
VDRCMD="$VDRPRG $VDRPLUGINS $*"
# vdr indítás, majd várakozás után az xbmc indítása
eval "$VDRCMD 2>&1" &
sleep 5
xbmc
killall -q -TERM vdr
