#! /bin/bash

# Ez a script verzióként (2.1 2.2 dev stb) megadott
# verzójú UB könyvtárakban törli a letöltött forásokat.


if [ "$#" != 1 ]; then
printf '%s\n' "A paraméterszám nem megfelelő!"
printf '%s\n' "Használat: source-del verzió "
exit
fi

DIST="$1"
DIR="$PWD"
cd /usr/src/UHUBUILD/UB-"$DIST"

for pkg in `ls -d */`; do

		rm /usr/src/UHUBUILD/UB-"$DIST"/"$pkg"/sources/*.* 2>/dev/null

done
cd "$DIR"
printf '%s\n' "A törlés befejeződött"
exit 0
