#!/bin/sh -eux

extensions="nemo-fileroller nemo-image-converter nemo-preview nemo-seahorse nemo-share"
for progs in ${extensions}; do
cd $progs
  autoreconf -vif
  ub_compile
cd ..
done

cd nemo-python
  ub_compile
