#!/bin/sh -eux

if [ "$UB_ARCH" = "amd64" ]; then
	tar -xzvf flash_player_npapi_linux-${UB_VERSION}-x86_64.tar.gz
else
	tar -xzvf flash_player_npapi_linux-${UB_VERSION}-i386.tar.gz
fi
rm -f flash_player_npapi_linux-*.tar.gz

libdir="$UB_INSTALLDIR/usr/lib"

cp -a usr "$UB_INSTALLDIR"/

mkdir -p "$libdir"/{firefox,mozilla}/plugins

install -m 755 libflashplayer.so "$libdir"/firefox/plugins/

rm -Rf "$UB_INSTALLDIR"/usr/lib/kde4
rm -Rf "$UB_INSTALLDIR"/usr/share/kde4

ln -s ../../firefox/plugins/libflashplayer.so "$libdir"/mozilla/plugins/
