#!/bin/sh -eux

if [ "$UB_ARCH" == "amd64" ];then
arch=x86_64
else
arch=i386
fi
install -Dm 755 "build/release-linux-${arch}/smokinguns.${arch}" "$UB_INSTALLDIR/usr/bin/smokinguns"
install -Dm 755 "build/release-linux-${arch}/smokinguns_dedicated.${arch}" "$UB_INSTALLDIR/usr/bin/smokinguns_dedicated"

install -Dm 644 "misc/smokinguns.png" "$UB_INSTALLDIR/usr/share/pixmaps/smokinguns.png"
