#!/bin/sh -eux

ls build
install -Dm 755 "build/release-linux-i386/smokinguns.i386" "$UB_INSTALLDIR/usr/bin/smokinguns"
install -Dm 755 "build/release-linux-i386/smokinguns_dedicated.i386" "$UB_INSTALLDIR/usr/bin/smokinguns_dedicated"

install -Dm 644 "misc/smokinguns.png" "$UB_INSTALLDIR/usr/share/pixmaps/smokinguns.png"

