#!/bin/sh -eux

sed -e 's|/CMAKE/|/cmake/|' -i CBLAS/CMakeLists.txt
install -d build
cd build
cmake .. \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_SKIP_RPATH=ON \
	-DBUILD_SHARED_LIBS=ON \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_Fortran_COMPILER=gfortran \
	-DLAPACKE=ON \
	-DCBLAS=ON
make
