#!/bin/sh -eux

install -m 755 pico/pico   "$UB_INSTALLDIR"/usr/bin/
install -m 755 pico/pilot  "$UB_INSTALLDIR"/usr/bin/
install -m 755 pine/pine   "$UB_INSTALLDIR"/usr/bin/
install -m 755 pine/rpdump "$UB_INSTALLDIR"/usr/bin/
install -m 755 pine/rpload "$UB_INSTALLDIR"/usr/bin/

install -m 644 doc/*.1 "$UB_INSTALLDIR"/usr/share/man/man1/
