#!/bin/sh -eux

#export QTDIR="/usr/lib/qt4"
sed -i 's|${QT_LIBRARIES}|${QT_LIBRARIES} ${OPENGL_LIBRARIES}|' CMakeLists.txt
sed -i "s|FIND_PACKAGE|FIND_PACKAGE(OpenGL REQUIRED)\nFIND_PACKAGE|" CMakeLists.txt
sed -i 's|/usr/local|/usr|' CMakeLists.txt
cmake -DCMAKE_INSTALL_PREFIX="/usr"
ub_make
