#!/bin/bash -eux

mkdir "$UB_INSTALLDIR"/usr/lib/mkinitramfs
cp init "$UB_INSTALLDIR"/usr/lib/mkinitramfs/
chmod 755 "$UB_INSTALLDIR"/usr/lib/mkinitramfs/init
cp  mkinitramfs "$UB_INSTALLDIR"/usr/sbin/
chmod 755 "$UB_INSTALLDIR"/usr/sbin/mkinitramfs
