#!/bin/sh -eux

cp bin/alarmclock "$UB_INSTALLDIR"/usr/bin/
cp bin/getgui "$UB_INSTALLDIR"/usr/bin/
cp bin/ggtimeutil "$UB_INSTALLDIR"/usr/bin/
mkdir -p "$UB_INSTALLDIR"/usr/share/getgui/examples
cp -a examples/. "$UB_INSTALLDIR"/usr/share/getgui/examples/
cp man/mangg/getgui.1 "$UB_INSTALLDIR"/usr/share/man/man1/
