#!/bin/sh -eux

export PATH=$PATH:$UB_COMPILEDIR/linux/bin32
cd src/dmd
ub_make \
	-f posix.mak \
	MODEL="32" \
	RELEASE=1
cd ../..
cd src/druntime
ub_make \
	-f posix.mak \
	MODEL="32" \
	RELEASE=1
cd ../..

cd src/phobos
ub_make \
	-f posix.mak \
	MODEL="32"
	RELEASE=1
cd ../..
