#!/bin/sh -eux

sed -i "/ADDITIONAL_OBJCFLAGS/s/=/= -fobjc-exceptions/" GNUmakefile

rm deps/Linux-deps/include/png.h
rm deps/Linux-deps/include/pngconf.h

if [ "$UB_ARCH" == "amd64" ]; then
	export UB_TARGET="x86_64-unknown-linux"
else
	export UB_TARGET="i686-gnu-linux"
fi
CC=gcc make AR="ar" RANLIB="ranlib" GNUSTEP_MAKEFILES="/usr/share/GNUstep/Makefiles" -f Makefile release-deployment
