#!/bin/sh -eux

ub_install

rm -rf "$UB_INSTALLDIR"/usr/share/doc/lives-"$UB_VERSION"/{AUTHORS,BUGS,ChangeLog,FEATURES,GETTING.STARTED,README,README.multi_encoder}
rm -f $UB_INSTALLDIR/usr/bin/lives
ln -s $UB_INSTALLDIR/usr/bin/lives-exe $UB_INSTALLDIR/usr/bin/lives
