#!/bin/sh -eux

ub_install

## remove this due to conflicts with icon-theme-hicolor
rm -rf "${UB_INSTALLDIR}"/usr/share/icons/hicolor

## PAM link for kdm and kscreensaver
mkdir -p "$UB_INSTALLDIR"/etc/pam.d
ln -s system-auth "$UB_INSTALLDIR"/etc/pam.d/kde
