#!/bin/sh -eux

ub_install

#We dont need separate desktop file for KDE
rm -f "$UB_INSTALLDIR"/usr/share/applications/synaptic-kde.desktop

sed -i -e 's|\[pt_PT\]|\[pt\]|g' \
  "$UB_INSTALLDIR"/usr/share/applications/synaptic.desktop
