#!/bin/sh -eux

cd gnu
aclocal
autoconf
rm -f config.{guess,sub}
cp /usr/share/automake-"$(automake --version|head -n1|sed -r 's/.*\) (.*)/\1/')"/config.{guess,sub} .
./configure --prefix=/usr
cd ..
export UB_MAKE_PROCS=1
make prepare
make
