#!/bin/sh -eux

PREFIX="$UB_INSTALLDIR/usr" ./install.sh

# fix configfiles
ub_replace "$UB_INSTALLDIR" "" "$UB_INSTALLDIR/etc/fpc.cfg"
ub_replace "$UB_INSTALLDIR" "" "$UB_INSTALLDIR/etc/fppkg.cfg"
ub_replace "$UB_INSTALLDIR" "" "$UB_INSTALLDIR/etc/fppkg/default"

# fix symlink
rm "$UB_INSTALLDIR/usr/bin/ppc386"
ln -s "../lib/fpc/$UB_VERSION/ppc386" "$UB_INSTALLDIR/usr/bin/ppc386"

# /usr/man -> /usr/share/man
rm -rf "$UB_INSTALLDIR"/usr/share/man
mv "$UB_INSTALLDIR"/usr/man "$UB_INSTALLDIR"/usr/share/

# install sources
mkdir -p "$UB_INSTALLDIR"/usr/src
mv fpc-${UB_VERSION} "$UB_INSTALLDIR"/usr/src/fpc

## Remove the unsupported PalmOS tree. It kills strip
#rm -rf "$UB_INSTALLDIR/usr/src/fpc-$UB_VERSION/rtl/palmos"

find "$UB_INSTALLDIR" -name CVS -type d -print0 | xargs -r -0 rm -rf
find "$UB_INSTALLDIR" -name .svn -type d -print0 | xargs -r -0 rm -rf
find "$UB_INSTALLDIR" -name .cvsignore -print0 | xargs -r -0 rm -rf

chown -Rh 0.0 "$UB_INSTALLDIR"
