#!/bin/sh -eux

#ub_install
python setup.py install --prefix=/usr --root="$UB_INSTALLDIR"
mkdir -p "$UB_INSTALLDIR"/usr/share/dbus-1/services
install -m644 misc/org.Coherence.service "$UB_INSTALLDIR"/usr/share/dbus-1/services/
