#!/bin/sh -eux

if [ "$UB_ARCH" == "amd64" ];then

cp usr/bin/cgc ${UB_INSTALLDIR}/usr/bin/
mkdir -p ${UB_INSTALLDIR}/usr/include/Cg
cp usr/include/Cg/* ${UB_INSTALLDIR}/usr/include/Cg/
cp usr/lib64/* ${UB_INSTALLDIR}/usr/lib/
cp -r usr/local/Cg ${UB_INSTALLDIR}/usr/share/

else

cp usr/bin/cgc ${UB_INSTALLDIR}/usr/bin/
mkdir -p ${UB_INSTALLDIR}/usr/include/Cg
cp usr/include/Cg/* ${UB_INSTALLDIR}/usr/include/Cg/
cp usr/lib/* ${UB_INSTALLDIR}/usr/lib/
cp -r usr/local/Cg ${UB_INSTALLDIR}/usr/share/

fi
