#!/bin/sh -eux

cd $UB_ARCH

cp usr/bin/cgc ${UB_INSTALLDIR}/usr/bin/
mkdir -p ${UB_INSTALLDIR}/usr/include/Cg
cp usr/include/Cg/* ${UB_INSTALLDIR}/usr/include/Cg/
if [ "$UB_ARCH" == "amd64" ];then
cp usr/lib64/* ${UB_INSTALLDIR}/usr/lib/
else
cp usr/lib/* ${UB_INSTALLDIR}/usr/lib/
fi
cp -r usr/local/Cg ${UB_INSTALLDIR}/usr/share/
