#!/bin/sh -eux

rm -r src/3rdparty/chromium/third_party/icu/source
mkdir -p build
cd build

export CFLAGS="-fno-delete-null-pointer-checks"
export CXXFLAGS="-fno-delete-null-pointer-checks"
qmake WEBENGINE_CONFIG+="use_nss use_system_icu use_proprietary_codecs use_system_ffmpeg" ../qtwebengine.pro
ub_make
