#!/bin/sh -eux

cd build

ub_install INSTALL_ROOT=$UB_INSTALLDIR

# Drop QMAKE_PRL_BUILD_DIR because reference the build dir
find "$UB_INSTALLDIR/usr/lib" -type f -name '*.prl' -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;

