#!/bin/sh -eux

python setup.py install --root="$UB_INSTALLDIR"

cp doc/initscript.example "$UB_INSTALLDIR"/etc/init.d/ufw

mkdir -p "$UB_INSTALLDIR"/etc/bash_completion.d
cp shell-completion/bash "$UB_INSTALLDIR"/etc/bash_completion.d/ufw
