#!/bin/sh -eux

ARCH="x86_64"
if [ "$UB_ARCH" != "amd64" ];then
    sed s%version_test_gt_cmp=gt%version_test_gt_cmp=lt% -i grub/util/grub-mkconfig_lib.in
    ARCH="i386"
fi
opts=" \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --disable-silent-rules \
    --enable-device-mapper \
    --enable-grub-mkfont \
    --enable-nls \
    --enable-grub-mount
    --with-grubdir=grub \
    --disable-werror \
 "

export FREETYPE="pkg-config freetype2"
export BUILD_FREETYPE="pkg-config freetype2"
export GRUB_CONTRIB=grub-extras

cp unifont-11.0.02.bdf grub/unifont.bdf

cp -r grub grub-bios
cp -r grub grub-efi
cp -r grub-extras grub-bios/

#grub-bios
cd grub-bios
./autogen.sh
./configure \
	$opts \
	--enable-efiemu \
	--target="i386" \
	--enable-boot-time \
	--with-platform="pc"
make -j2

# efi
cd ../grub-efi
./autogen.sh
./configure \
	$opts \
	--disable-efiemu \
	--target=$ARCH \
    --enable-boot-time \
	--with-platform="efi"
make -j2

# grub-emu
cd ../grub
./autogen.sh
./configure \
	$opts \
	--enable-grub-emu-usb=no \
	--enable-grub-emu-sdl=no \
	--disable-grub-emu-pci \
	--target=$ARCH \
	--with-platform="emu"
    make -j2
