#!/bin/sh -eux

# build nbgrub, pxegrub, stage2.net
ub_compile \
	--disable-auto-linux-mem-opt \
	--enable-diskless \
	--disable-{ext2fs,ffs,ufs2,minix,reiserfs,reiser4,vstafs,jfs,xfs,iso9660} \
	--enable-{3c595,3c90x,e1000,eepro100} \
	--enable-{pcnet32,rtl8139,sis900,sundance,via-rhine}

mv stage2/stage2{,.net}
mv stage2/stage2_eltorito{,.net}
mv stage2/{stage2{,_eltorito}.net,{nb,pxe}grub} "$UB_OBJECTDIR"/

# clean
make clean

# apply splashscreen patches
for i in *.patch*; do
	case "$i" in
		*.patch)
			patch -p1 <"$i"
			;;
		*.patch0)
			patch -p0 <"$i"
			;;
	esac
done

# build the rest
ub_compile \
	--disable-reiser4 \
	--disable-auto-linux-mem-opt
