#!/bin/sh -eux

ARCH="x86_64"
if [ "$UB_ARCH" != "amd64" ];then
    ARCH="i386"
fi

#doksi

cd grub
cp AUTHORS COPYING NEWS README THANKS TODO ../
cd ..

# grub-efi

cd grub-efi
    make DESTDIR="${UB_INSTALLDIR}/" bashcompletiondir="/usr/share/bash-completion/completions" install
    rm -f "${UB_INSTALLDIR}/usr/lib/grub/${ARCH}-efi"/*.module
    rm -f "${UB_INSTALLDIR}/usr/lib/grub/${ARCH}-efi"/*.image
    rm -f "${UB_INSTALLDIR}/usr/lib/grub/${ARCH}-efi"/{kernel.exec,gdb_grub,gmodule.pl}
cd ..

# grub-emu

cd grub
    make DESTDIR="${UB_INSTALLDIR}/" bashcompletiondir="/usr/share/bash-completion/completions" install
    rm -f "${UB_INSTALLDIR}/usr/lib/grub/${ARCH}-emu"/*.module
    rm -f "${UB_INSTALLDIR}/usr/lib/grub/${ARCH}-emu"/*.image
    rm -f "${UB_INSTALLDIR}/usr/lib/grub/${ARCH}-emu"/{kernel.exec,gdb_grub,gmodule.pl}
cd ..

# bios & common

cd grub-bios
    make DESTDIR="${UB_INSTALLDIR}/" bashcompletiondir="/usr/share/bash-completion/completions" install
    rm -f "${UB_INSTALLDIR}/usr/lib/grub/i386-pc"/*.module
    rm -f "${UB_INSTALLDIR}/usr/lib/grub/i386-pc"/*.image
    rm -f "${UB_INSTALLDIR}/usr/lib/grub/i386-pc"/{kernel.exec,gdb_grub,gmodule.pl}
