#!/bin/sh -eux

ub_install
mkdir -p "${UB_INSTALLDIR}"/usr/share/info
install -D -m644 doc/enblend.info "${UB_INSTALLDIR}"/usr/share/info/enblend.info
install -D -m644 doc/enfuse.info "${UB_INSTALLDIR}"/usr/share/info/enfuse.info
