#!/bin/sh -eux

ub_install

# mozilla plugin
mkdir -p "$UB_INSTALLDIR"/usr/lib/mozilla/plugins
for i in "$UB_INSTALLDIR"/usr/lib/firefox/plugins/*.so; do
	ln -s ../../firefox/plugins/"${i##*/}" "$UB_INSTALLDIR"/usr/lib/mozilla/plugins/
done
