#!/bin/sh -eux

mkdir -p $UB_INSTALLDIR/usr/lib/thunderbird-bin
if [ "$UB_ARCH" == "i386" ];then
wget https://ftp.mozilla.org/pub/thunderbird/releases/${UB_VERSION/~/}/linux-i686/hu/thunderbird-${UB_VERSION/~/}.tar.bz2
else
wget https://ftp.mozilla.org/pub/thunderbird/releases/${UB_VERSION/~/}/linux-x86_64/hu/thunderbird-${UB_VERSION/~/}.tar.bz2
fi

tar -xf thunderbird-${UB_VERSION/~/}.tar.bz2
rm -f thunderbird-${UB_VERSION/~/}.tar.bz2
cd thunderbird
cp -a * $UB_INSTALLDIR/usr/lib/thunderbird-bin/

_vendorjs="$UB_INSTALLDIR/usr/lib/thunderbird-bin/defaults/preferences/vendor.js"
install -Dm644 /dev/stdin "$_vendorjs" <<END
// Use LANG environment variable to choose locale
pref("intl.locale.matchOS", true);

// Disable default mailer checking.
pref("mail.shell.checkDefaultMail", false);

// Don't disable our bundled extensions in the application directory
pref("extensions.autoDisableScopes", 11);
pref("extensions.shownSelectionUI", true);
END

# icons
for i in 16 22 24 32 48 256; do
    install -d "$UB_INSTALLDIR"/usr/share/icons/hicolor/${i}x${i}/apps/
    ln -s /usr/lib/thunderbird-bin/chrome/icons/default/default$i.png \
          "$UB_INSTALLDIR"/usr/share/icons/hicolor/${i}x${i}/apps/thunderbird-bin.png
done

  # Use system-provided dictionaries
  # rm -r "$UB_INSTALLDIR"/usr/lib/thunderbird-bin/dictionaries # Not in 68.0
  ln -Ts /usr/share/myspell "$UB_INSTALLDIR"/usr/lib/thunderbird-bin/dictionaries
  ln -Ts /usr/share/hyphen "$UB_INSTALLDIR"/usr/lib/thunderbird-bin/hyphenation

# Use system certificates
  ln -sf /usr/lib/libnssckbi.so "$UB_INSTALLDIR"/usr/lib/thunderbird-bin/libnssckbi.so

rm -f "$UB_INSTALLDIR"/usr/lib/thunderbird-bin/thunderbird
rm -f "$UB_INSTALLDIR"/usr/bin/thunderbird
ln -s /usr/lib/thunderbird-bin/thunderbird-bin "$UB_INSTALLDIR"/usr/bin/thunderbird-bin

exit
cd "$UB_OBJECTDIR"

ub_install

rm -f "$UB_INSTALLDIR"/usr/lib/thunderbird/thunderbird
rm -f "$UB_INSTALLDIR"/usr/bin/thunderbird
ln -s /usr/lib/thunderbird/thunderbird "$UB_INSTALLDIR"/usr/bin/thunderbird

if [ ! -f "$UB_INSTALLDIR"/usr/lib/thunderbird/run-mozilla.sh ]; then
	cp "$UB_COMPILEDIR"/build/unix/run-mozilla.sh "$UB_INSTALLDIR"/usr/lib/thunderbird/run-mozilla.sh
fi

mkdir -p "$UB_INSTALLDIR"/usr/lib/thunderbird/distribution/extensions/langpack-hu@thunderbird.mozilla.org
cp -aR "$UB_COMPILEDIR"/langpack-hu/. "$UB_INSTALLDIR"/usr/lib/thunderbird/distribution/extensions/langpack-hu@thunderbird.mozilla.org/

# install icons
for i in 16 22 24 32 48 64 128 256; do
    install -Dm644 "$UB_COMPILEDIR"/comm/mail/branding/thunderbird/default${i}.png \
      "$UB_INSTALLDIR/usr/share/icons/hicolor/${i}x${i}/apps/thunderbird.png"
done
cp "$UB_COMPILEDIR"/comm/mail/branding/thunderbird/default48.png "$UB_INSTALLDIR"/usr/share/pixmaps/thunderbird.png
