#!/bin/sh -eux

export UB_MAKE_PROCS=1
export CXXFLAGS='-std=gnu++98 -flifetime-dse=1'
ub_compile \
	--prefix=/usr/lib/firebird \
	--enable-superserver=yes \
	--with-system-editline=yes \
	--with-system-icu
