#!/bin/sh -eux

mkdir -p $UB_INSTALLDIR/usr/lib/vdr
make USEFSH=1 \
  VIDEODIR=/var/vdr/video \
  CONFDIR=/var/vdr/config \
  PREFIX=/usr \
  MANDIR=/usr/share/man \
  DESTDIR=$UB_INSTALLDIR \
  INCDIR=/usr/include/vdr \
  PARALELL=PARALLEL_32_INT
