#!/bin/sh -eux

ub_compile \
	--enable-sdl \
	--enable-xine \
	--enable-mng \
	--enable-imlib2 \
	--enable-gstreamer \
	--enable-zlib \
	--enable-x11 \
	--disable-vnc \
	--disable-osx \
	--enable-video4linux2 \
	--enable-voodoo \
	--enable-mesa
