#!/bin/sh -eux

ub_compile \
	--enable-plugins \
	--enable-cpu-level=6 \
	--enable-ne2000 \
	--enable-pci \
	--enable-usb \
	--enable-repeat-speedups \
	--enable-fast-function-calls \
	--enable-disasm \
	--enable-all-optimizations \
	--enable-readline \
	--enable-fpu \
	--enable-3dnow \
	--enable-x86-debugger \
	--enable-cdrom \
	--enable-sb16=linux \
	--enable-gameport \
	--enable-gdb-stub \
	--enable-iodebug \
	--enable-xpm \
	--enable-clgd54xx \
	--with-x11 \
	--with-sdl
