#!/bin/sh -eux

ub_install

mkdir -p "$UB_INSTALLDIR"/usr/share/libdate
cp -a cal.c "$UB_INSTALLDIR"/usr/share/libdate/
cp -a datetest "$UB_INSTALLDIR"/usr/share/libdate/
cp -a testsuite "$UB_INSTALLDIR"/usr/share/libdate/
mkdir -p "$UB_INSTALLDIR"/usr/share/doc/libdate
cp -a doc/html "$UB_INSTALLDIR"/usr/share/doc/libdate/
cp -a doc/man "$UB_INSTALLDIR"/usr/share/
