#!/bin/sh -eux

ub_compile \
	--with-udev-dir=/usr/lib/udev/ \
	--enable-more-warnings=no \
	--enable-ifupdown \
	--enable-modify-system \
	--enable-concheck \
	--with-session-tracking=systemd \
	--with-suspend-resume=systemd \
	--with-nmtui
