#!/bin/sh -eux

ub_install

mkdir -p $UB_INSTALLDIR/usr/lib/xorg/extra-modules

cd rgb-*
ub_install
mv $UB_INSTALLDIR/usr/lib/xorg/modules/extensions/libglx.so $UB_INSTALLDIR/usr/lib/xorg/modules/extensions/libglx.so.xorg
