#!/bin/sh -eux

NOCONFIGURE=1 ./autogen.sh
ub_compile \
	--disable-distribution \
	--disable-gconf \
	--disable-xml \
	--enable-dbus \
	--disable-gnome2 \
	--enable-gnome3 \
	--enable-xfce \
	--enable-mate

