#!/bin/sh -eux

sed -i -e '/^DISTRIBUTION_HOME/s/\/$//' frontend/gtkmm/src/Makefile.*
NOCONFIGURE=1 ./autogen.sh
export CXXFLAGS='-std=c++11'
ub_compile \
	--enable-dbus \
	--disable-xml \
	--enable-gnome3
