#!/bin/sh -eux

ub_install \
	PREFIX=/usr

# Verify that the magic patch really worked.
if grep -q '@DATADIR@' "$UB_INSTALLDIR"/usr/lib/perl5/*/*/*/fb_stuff.pm; then
	echo "Compilation failed. Try again."
	exit 1
fi
