#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/PlusDesktop
cp -a . "$UB_INSTALLDIR"/usr/share/PlusDesktop
ln -s ../PlusDesktop/PlusDesktop.ico \
	"$UB_INSTALLDIR"/usr/share/pixmaps/plusdesktop.ico
