#!/bin/sh -eux

ub_install

ln -s /usr/share/lirc/contrib/irman2lirc ${UB_INSTALLDIR}/usr/bin/irman2lirc

# Az alap hardver adatbázis
cp doc/lirc.hwdb ${UB_INSTALLDIR}/usr/share/lirc/lirc.hwdb

# Fedora régi remote adatok
mkdir -p ${UB_INSTALLDIR}/usr/share/lirc 
mv usr/share/lirc-remotes ${UB_INSTALLDIR}/usr/share/lirc/remotes

# Az alap kernel rules
mkdir -p ${UB_INSTALLDIR}/etc/udev/rules.d
cp contrib/60-lirc.rules ${UB_INSTALLDIR}/etc/udev/rules.d/

# !! ez letiltaná a kernel lirc-et, talán egy új csomagba kellene tenni !!
cp contrib/99-remote-control-lirc.rules ${UB_INSTALLDIR}/etc/udev/rules.d/
