#!/bin/sh -eux

# radio, radio-capture: libv4l

CFLAGS="-O2 -march=i686 -mtune=generic -fomit-frame-pointer -I/usr/include/directfb" \
./configure \
	--prefix=/usr \
	--datadir=/usr/share/mplayer \
	--confdir=/etc/mplayer \
	--codecsdir=/usr/lib/codecs \
	--disable-termcap \
	--enable-runtime-cpudetection \
	--language="hu bg cs de dk el en es fr it ja ko mk nb nl pl ro ru sk sv tr uk pt_BR zh_CN zh_TW" \
	--enable-menu \
	--enable-fribidi \
	--enable-bl \
	--enable-xvmc \
	--enable-mga \
	--enable-xmga \
	--enable-vdpau \
	--enable-libgsm \
	--disable-radio \
	--disable-radio-capture \
	--enable-gui \
	--enable-directfb \
	--extra-ldflags="-lfribidi"
ub_make
