#!/bin/sh -eux

ub_install
rm "$UB_INSTALLDIR"/usr/lib/libguile-2.0.so.22.7.2-gdb.scm
# just for compatibility
ln -sf guile "$UB_INSTALLDIR"/usr/bin/guile2
ln -sf guile-tools "$UB_INSTALLDIR"/usr/bin/guile2-tools
