#!/bin/sh -eux

export UB_MAKE_PROCS=1
mkdir -p include/curl
touch include/curl/types.h
ub_compile \
	--enable-libxml2-backend	\
	--disable-abyss-server		\
	--disable-wininet-client	\
	--disable-libwww-client
