#!/bin/sh -eux

ub_install

mkdir -p "$UB_INSTALLDIR"/etc/pango
pango/pango-querymodules "$UB_INSTALLDIR"/usr/lib/pango/*/modules/*.so | \
  sed "s@$UB_INSTALLDIR@@g" > "$UB_INSTALLDIR"/etc/pango/pango.modules
