#!/bin/sh -eux

export QTDIR="/usr/lib/qt5"
export MOC=/usr/lib/qt5/bin/moc
export UIC=/usr/lib/qt5/bin/uic
cd src
ub_make IPEPREFIX=/usr

cd ../ipepresenter
make

cd ../pdftoipe
make

cd ../figtoipe
make

cd ../ipe5toxml
make
