#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/lib/monkeystudio/
cp -f -r bin/plugins/* "$UB_INSTALLDIR"/usr/lib/monkeystudio/
mkdir -p "$UB_INSTALLDIR"/usr/share/monkeystudio/
cp -f -r datas/* "$UB_INSTALLDIR"/usr/share/monkeystudio/
install -m 755 -p bin/monkeystudio "$UB_INSTALLDIR"/usr/bin/
