#!/bin/bash -eux

case "$UB_VERSION" in
	*.*.*)
		VERSION_BASE="${UB_VERSION/\~/-}-${UB_RELEASE}"
		;;
	*.*~*)
		VERSION_BASE="${UB_VERSION/\~/.0-}-${UB_RELEASE}"
		;;
	*.*)
		VERSION_BASE="${UB_VERSION}.0-${UB_RELEASE}"
		;;
	*)
		exit 1
		;;
esac

export KBUILD_BUILD_TIMESTAMP="$(LC_ALL=C LANG=C date)"

NUMCPUS="$(grep ^processor /proc/cpuinfo|wc -l)"

rm -f localversion*

# for ARCH in x86_64 i386; do
ARCH="i386"
VERSION="${VERSION_BASE}.$ARCH"
ub_replace "^EXTRAVERSION =[\t ]*\(\.\([0-9]\+\)\)*.*" "EXTRAVERSION = \1-${VERSION#*-}" Makefile

cp .config."$ARCH" .config
cp .config."$ARCH" arch/x86/configs/"$ARCH"_defconfig

# 4.4-től nem igazán jó, CONFIG_SYSTEM_TRUSTED_KEYS="" jön pluszban, de nem kell module sig
# make ARCH="$ARCH" oldconfig
# diff -u <(grep -v '^#' .config|sort) <(grep -v '^#' arch/x86/configs/"$ARCH"_defconfig|sort)

make prepare
yes "" | make config >/dev/null

make ARCH="$ARCH" -j"$NUMCPUS" scripts
make ARCH="$ARCH" -j"$NUMCPUS" bzImage
make ARCH="$ARCH" -j"$NUMCPUS" modules

# done

