#!/bin/bash -eux

case "$UB_VERSION" in
	*.*.*)
		VERSION_BASE="${UB_VERSION/\~/-}-${UB_RELEASE}"
		;;
	*.*~*)
		VERSION_BASE="${UB_VERSION/\~/.0-}-${UB_RELEASE}"
		;;
	*.*)
		VERSION_BASE="${UB_VERSION}.0-${UB_RELEASE}"
		;;
	*)
		exit 1
		;;
esac

export KBUILD_BUILD_TIMESTAMP="$(LC_ALL=C LANG=C date)"

# mkinitrd
cat >"$UB_INSTALLDIR"/usr/sbin/mkinitrd-installedkernel <<END
#!/bin/sh

mkinitrd $VERSION_BASE

ln -sf initrd-$VERSION_BASE.gz /boot/initrd.i386.gz
ln -sf initrd-$VERSION_BASE.gz /boot/initrd-$VERSION_BASE.i386.gz
ln -sf initrd-$VERSION_BASE.gz /boot/initrd.x86_64.gz
ln -sf initrd-$VERSION_BASE.gz /boot/initrd-$VERSION_BASE.x86_64.gz

END

chmod 755 "$UB_INSTALLDIR"/usr/sbin/mkinitrd-installedkernel

cp -al "$UB_OBJECTDIR"/. "$UB_INSTALLDIR"/

chmod -R a+rX,u+w,go-w "$UB_INSTALLDIR"

