#!/bin/sh -eux

cd src
mkdir -p ${UB_INSTALLDIR}/usr/share/games/sauerbraten/bin
install -Dm 755 sauer_client sauer_server ${UB_INSTALLDIR}/usr/share/games/sauerbraten/bin/

cd ..
mkdir -p "${UB_INSTALLDIR}"/usr/share/games/sauerbraten
cp -r {data,packages} "${UB_INSTALLDIR}"/usr/share/games/sauerbraten/
