#!/bin/sh -eux

ub_install
mv $UB_INSTALLDIR/usr/games/powermanga $UB_INSTALLDIR/usr/bin/
rmdir  $UB_INSTALLDIR/usr/games
mkdir -p $UB_INSTALLDIR/usr/share/{applications,pixmaps}
mv powermanga.desktop $UB_INSTALLDIR/usr/share/applications/
mv powermanga.xpm $UB_INSTALLDIR/usr/share/pixmaps/
for f in powermanga.hi-easy powermanga.hi powermanga.hi-hard ; do
	touch "$UB_INSTALLDIR"/usr/share/games/powermanga/${f}
	chmod 666 "$UB_INSTALLDIR"/usr/share/games/powermanga/${f}
done
