#!/bin/sh -eux

export CFLAGS="-fno-lto"
# compile fix
sed -r -i 's/\blibsystemd-(login|journal|id128|daemon).c \\/\\/' Makefile.am
autoreconf -vif

ub_compile \
	--with-pamlibdir=/lib/security \
	--with-ntp-servers=pool.ntp.org \
	--enable-manpages \
	--enable-compat-libs \
	--enable-split-usr \
	--disable-microhttpd
