#!/bin/sh -eux

ub_install

for i in udev{monitor,trigger,settle,control}; do
	ln -s udevadm "$UB_INSTALLDIR"/usr/bin/"$i"
done

for i in udev{info,test}; do
	ln -s udevadm "$UB_INSTALLDIR"/usr/bin/"$i"
done

find "$UB_INSTALLDIR"/usr/lib/udev/ -type f -maxdepth 1 | while read n; do	
	name="$(basename $n)"
	ln -s ../usr/lib/udev/"$name" "$UB_INSTALLDIR"/sbin/"$name"
done

for file in "$UB_INSTALLDIR"/usr/lib/udev/rules.d/*.rules; do
	for group in cdrom dialout disk floppy input kmem utmp uucp; do
		sed -e "s/GROUP=\"$group\"/GROUP=\"media\"/g" -i "$file"
	done
done

find "$UB_INSTALLDIR"/ -type f -name '*.la' -print0 | xargs -r0 rm
ln -s /usr/lib/systemd/systemd-udevd "$UB_INSTALLDIR"/sbin/udevd

for i in halt poweroff reboot; do
	ln -s systemctl "$UB_INSTALLDIR"/usr/bin/$i
done

for target in graphical multi-user; do
	mkdir -p "$UB_INSTALLDIR"/etc/systemd/system/"$target".target.wants
	ln -s /usr/lib/systemd/system/postboot_run.service "$UB_INSTALLDIR"/etc/systemd/system/$target.target.wants/postboot_run.service
done
