#!/bin/sh -eux

sed -ri 's/^=item ([0-9]+)/=item C<\1>/' doc/{apps,crypto,ssl}/*.pod

# A -O3 veszélyes
ub_replace -O3 -O2 Configure

if [ "$UB_ARCH" == "amd64" ];then
opts=" --libdir=lib linux-x86_64 enable-ec_nistp_64_gcc_128"
else
opts=" linux-elf"
fi

./Configure \
	--prefix=/usr \
	--openssldir=/etc/ssl \
	$opts \
	enable-tlsext \
	shared \
	no-sse2 \
	zlib-dynamic

make depend
make
