#!/bin/sh -eux

sed -ri 's/^=item ([0-9]+)/=item C<\1>/' doc/{apps,crypto,ssl}/*.pod

./Configure \
	--prefix=/usr \
	--openssldir=/etc/ssl \
	enable-tlsext \
	shared \
	no-sse2 \
	linux-elf \
	zlib-dynamic
make
