#!/bin/sh -eux

export PATH="$PATH:/usr/lib/java/bin"
export CLASSPATH="/usr/share/jdictionary/jdictionary.jar"

jar -xf *.jar

jad -sjava Buffer MySelf Resources
patch -p0 <read-utf8-dictionary.patch
javac -g Buffer.java MySelf.java Resources.java

iconv -f ISO-8859-1 -t UTF-8 <resources/dictionary/Swedish_Interlingua >resources/dictionary/Swedish_Interlingua.new
mv resources/dictionary/Swedish_Interlingua.new resources/dictionary/Swedish_Interlingua
if [ -f dictionary.patch ]; then
	patch -p0 <dictionary.patch
fi

iconv -f ISO-8859-2 -t UTF-8 <InfoSheet >InfoSheet.new
mv InfoSheet.new InfoSheet

jar -uf *.jar Buffer.class resources/dictionary/Swedish_Interlingua InfoSheet
