#!/bin/sh -eux

cd "$UB_OBJECTDIR"

ub_install

mv "$UB_INSTALLDIR"/usr/lib/xulrunner-"$UB_VERSION" "$UB_INSTALLDIR"/usr/lib/xulrunner
ln -s xulrunner "$UB_INSTALLDIR"/usr/lib/xulrunner-"$UB_VERSION"

mv "$UB_INSTALLDIR"/usr/include/xulrunner-"$UB_VERSION" "$UB_INSTALLDIR"/usr/include/xulrunner
ln -s xulrunner "$UB_INSTALLDIR"/usr/include/xulrunner-"$UB_VERSION" 

mv "$UB_INSTALLDIR"/usr/share/idl/xulrunner-"$UB_VERSION" "$UB_INSTALLDIR"/usr/share/idl/xulrunner
ln -s xulrunner "$UB_INSTALLDIR"/usr/share/idl/xulrunner-"$UB_VERSION"

mv "$UB_INSTALLDIR"/usr/lib/xulrunner-devel-"$UB_VERSION" "$UB_INSTALLDIR"/usr/lib/xulrunner-devel
ln -s xulrunner-devel "$UB_INSTALLDIR"/usr/lib/xulrunner-devel-"$UB_VERSION"

ln -fs sdk/lib "$UB_INSTALLDIR"/usr/lib/xulrunner-devel/lib

# remove version from .pc's
sed -i "s/-$UB_VERSION$//" "$UB_INSTALLDIR"/usr/lib/pkgconfig/*.pc

# remove docs from /usr/lib/xulrunner
rm -rf "$UB_INSTALLDIR"/usr/lib/xulrunner/LICENSE
rm -rf "$UB_INSTALLDIR"/usr/lib/xulrunner/README.txt
