#!/bin/sh -eux

cd unix
make \
	INSTALL_ROOT="$UB_INSTALLDIR" \
	install \
	install-private-headers

for i in tkUnix*.h ../generic/tk*.h; do
	sed -e 's,\.\./[^/]*/,,g' <"$i" >"$UB_INSTALLDIR/usr/include/${i##*/}"
done
ln -s "wish$UB_VERSION_HEAD2" "$UB_INSTALLDIR"/usr/bin/wish
chmod -x "$UB_INSTALLDIR"/usr/lib/*.a

