#!/bin/sh -eux

#ub_compile
cd ext
mkdir -p gmock-1.6.0
mkdir -p gtest-1.6.0
unzip -x gmock-1.6.0.zip -d gmock-1.6.0
unzip -x gtest-1.6.0.zip -d gtest-1.6.0
tar -zxvf openssl-1.0.2.tar.gz
cd ..
cmake .
ub_make
