#!/bin/sh -eux

ub_install

mkdir -p "$UB_INSTALLDIR"/usr/lib/lua/5.1
mv "$UB_INSTALLDIR"/usr/lib/lua/gv.so "$UB_INSTALLDIR"/usr/lib/lua/5.1/
rm -rf "$UB_INSTALLDIR"/usr/share/graphviz/doc/{AUTHORS,COPYING,ChangeLog,NEWS}
