#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/lib/java
cp -ar . "$UB_INSTALLDIR"/usr/lib/java/

# fix directory name of Japanese man pages
rm "$UB_INSTALLDIR"/usr/lib/java/man/ja
mv "$UB_INSTALLDIR"/usr/lib/java/man/ja_JP.UTF-8 "$UB_INSTALLDIR"/usr/lib/java/man/ja

# move man pages to /usr/share/man
rm -rf "$UB_INSTALLDIR"/usr/share/man
mv "$UB_INSTALLDIR"/usr/lib/java/man "$UB_INSTALLDIR"/usr/share/

# avoid man page conflict with other packages
for i in $(find "$UB_INSTALLDIR"/usr/share/man -type f); do
	mv "$i" "$i"java
done

# documentation
mkdir -p "$UB_INSTALLDIR"/usr/share/doc/Packages/java-{jre,jdk}
ln -s /usr/lib/java/jre/{COPYRIGHT,LICENSE,README,THIRDPARTYLICENSEREADME.txt,Welcome.html} "$UB_INSTALLDIR"/usr/share/doc/Packages/java-jre/
ln -s /usr/lib/java/{COPYRIGHT,LICENSE,README.html,THIRDPARTYLICENSEREADME.txt} "$UB_INSTALLDIR"/usr/share/doc/Packages/java-jdk/

# desktop
mv "$UB_INSTALLDIR"/usr/lib/java/jre/lib/desktop/{applications,icons,mime} "$UB_INSTALLDIR"/usr/share/
rm -Rf "$UB_INSTALLDIR"/usr/lib/java/jre/lib/desktop

# firefox plugin
mkdir -p "$UB_INSTALLDIR"/usr/lib/firefox/plugins
ln -s /usr/lib/java/jre/lib/i386/libnpjp2.so "$UB_INSTALLDIR"/usr/lib/firefox/plugins/

# mozilla plugin
mkdir -p "$UB_INSTALLDIR"/usr/lib/mozilla/plugins
ln -s /usr/lib/java/jre/lib/i386/libnpjp2.so "$UB_INSTALLDIR"/usr/lib/mozilla/plugins/

# fix permissions
chmod -R a+rX,u+w,go-w "$UB_INSTALLDIR"

# ffmpeg < 0.11, 2.0 kellene
rm -f "$UB_INSTALLDIR"/usr/lib/java/jre/lib/i386/libavplugin-{53,54}.so

