#!/bin/sh -eux

ub_replace -O3 -O2 lib-src/libvorbis/configure.ac
ub_replace -O3 -O2 lib-src/soundtouch/source/SoundTouch/Makefile.in
ub_replace -O3 -O2 lib-src/libflac/configure.ac
ub_replace -O3 -O2 lib-src/sbsms/configure.ac
rm -f CMakeLists.txt
export WX_CONFIG=/usr/bin/wx-config
autoreconf -ifv
#UB_CONFIGURE_NO_DISABLE_STATIC=yes \
export WX_CONFIG=/usr/bin/wx-config
./configure \
    --prefix=/usr \
	--disable-dynamic-loading \
    --with-libsndfile="system" \
    --with-ffmpeg="system" \
    --with-expat="system" \
    --with-lame="system" \
    --with-portaudio \
    --with-portmidi \
    --with-libflac \
    --with-libid3tag \
    --with-libsamplerate \
    --with-sbsms \
    --with-soundtouch \
    --with-libtwolame \
    --with-libvorbis \
    --with-lv2
ub_make
