#!/bin/sh -eux

export CXXFLAGS=-std=c++11

ub_compile \
	--enable-gpl \
	--enable-gpl3 \
	--qimage-libdir=/usr/lib/qt5/lib \
	--qimage-includedir=/usr/lib/qt5/include \
	--avformat-swscale \
	--target-arch=i386 \
#	--avformat-vdpau
