#!/bin/sh -eux

rm -r misc/liblua misc/libphysfs
export QTDIR=/usr/lib/qt4
UB_MAKE_PROCS=1
ub_compile \
	-DNOSERVER=1 \
	-DMINIMAL_FLAGS=1 \
	-DNOVIDEOREC=1 \
	-DGHFLAGS=-dynamic \
	-DFONTS_DIRS="/usr/share/fonts/TTF" \
	-DFPFLAGS="-k/usr/lib/libgcc_s.so.1"
	#Helping libc >= 2.17, see launchpad bug #1179850
