#!/bin/sh -eux

mkdir build
cd build
../configure \
	--version="$UB_VERSION" \
	--install-prefix="$UB_INSTALLDIR"/usr \
	--install-cgi-prefix="$UB_INSTALLDIR"/usr/share/libh
export UB_MAKE_PROCS=1
ub_make
