#!/bin/sh -eux

# antlr3 3.4 jó csak, a 3.5.2-vel nem fordul le!

export JAVA=/usr/lib/java/jre/bin/java

sed -i \
	-e "s#antlr_java_prefixes=.*#antlr_java_prefixes=$UB_COMPILEDIR#" \
	-e "s|-Werror||g" \
	configure{,.ac}

ub_compile
