#!/bin/bash -eux

# A -O3 veszélyes
ub_replace -O3 -O2 src/png/scripts/makefile.linux
ub_replace -O3 -O2 wxPython/config.py
ub_replace -O3 -O2 wxPython/wx/build/config.py

./configure \
	--prefix=/usr \
	--libdir=/usr/lib \
	--with-gtk=2 \
	--with-opengl \
	--enable-unicode \
	--enable-graphics_ctx \
	--disable-optimize \
	--enable-mediactrl \
	--with-regex=sys \
	--with-libpng=sys \
	--with-libxpm=sys \
	--with-libjpeg=sys \
	--with-libtiff=sys \
	--disable-precomp-headers

cd wxPython

python2 setup.py \
	WXPORT=gtk2 \
	UNICODE=1 \
	WX_CONFIG=/usr/bin/wx-config2 \
	build
