#!/bin/sh -eux

libtoolize --force --automake --copy
aclocal --force
autoheader --force
automake \
     --gnu \
     --force-missing \
     --add-missing \
     --copy
autoconf \
     --force
ub_compile
