#!/bin/sh -eux

sed -i -e 's@modules/afmongodb/libmongo-client@@' -e 's@lib/jsonc@@' autogen.sh

./autogen.sh
ub_compile \
	--with-systemdsystemunitdir=/usr/lib/systemd/system \
	--with-embedded-crypto \
	--with-libmongo-client=no \
	--with-jsonc=system \
	--enable-spoof-source \
	--sysconfdir=/etc/syslog-ng \
	--localstatedir=/var/lib/syslog-ng \
	--datadir=/usr/share/syslog-ng
