#!/bin/sh -eux

ub_install

install -d -m 777 "$UB_INSTALLDIR"/var/vdr/config/themes \
	"$UB_INSTALLDIR"/var/vdr/config/plugins/skinelchi/{logos,hqlogos}
install -m 777 themes/* "$UB_INSTALLDIR"/var/vdr/config/themes/
