#!/bin/sh -eux

python3 setup.py install --root="$UB_INSTALLDIR"
mv "${UB_INSTALLDIR}"/usr/bin/alembic "${UB_INSTALLDIR}"/usr/bin/alembic3

python setup.py install --root="$UB_INSTALLDIR"

mkdir -p "${UB_INSTALLDIR}"/usr/share/doc/alembic
cp -r docs "${UB_INSTALLDIR}"/usr/share/doc/alembic/
