#!/bin/sh -eux

make user_install \
	DESTDIR="$UB_INSTALLDIR" \
	PREFIX="/usr" \
	MANDIR="/usr/share/man"

mkdir -p "$UB_INSTALLDIR"/usr/share/doc/Packages/lmsensors/examples
cp -r prog/{rrd,tellerstats} "$UB_INSTALLDIR"/usr/share/doc/Packages/lmsensors/examples/

rm -rf "$UB_INSTALLDIR"/usr/include/linux
rm -rf "$UB_INSTALLDIR"/usr/lib/libsensors.a
