#!/bin/sh -eux

if [ "$UB_ARCH" == "amd64" ];then
    echo "Csak 32 bites csomag készíthető!"
    exit 1
else
arch="i386"
fi

dpkg-deb -x opera-stable_${UB_VERSION}_${UB_ARCH}.deb .
rm -f opera-stable_${UB_VERSION}_*.deb

cd usr/share/applications
patch -i $UB_SRCDIR/patches/desktop.patch.skip
cd -
cp -r "$UB_COMPILEDIR"/usr "$UB_INSTALLDIR"/

rm -Rf "$UB_INSTALLDIR"/usr/share/{lintian,menu}

mkdir -p "$UB_INSTALLDIR"/usr/lib/opera/
cp -r "$UB_INSTALLDIR"/usr/lib/${arch}-linux-gnu/opera "$UB_INSTALLDIR"/usr/lib/
rm -Rf "$UB_INSTALLDIR"/usr/lib/${arch}-linux-gnu

ln -sf /usr/lib/opera/opera "$UB_INSTALLDIR"/usr/bin/opera
