#!/bin/sh -eux

ub_install
mv "$UB_INSTALLDIR"/usr/bin/ide "$UB_INSTALLDIR"/usr/bin/ecere
mv "$UB_INSTALLDIR"/usr/share/ecere/doc/Ecere* "$UB_INSTALLDIR"/usr/share/ecere/doc/Ecere.pdf
chmod -x "$UB_INSTALLDIR"/usr/share/ecere/doc/Ecere.pdf
chmod -x "$UB_INSTALLDIR"/usr/share/applications/ecere.desktop
if [ -d "$UB_INSTALLDIR"/usr/lib32 ]; then
	cp -a "$UB_INSTALLDIR"/usr/lib32/*.* "$UB_INSTALLDIR"/usr/lib/;
	rm "$UB_INSTALLDIR"/usr/lib32/*.*
	rmdir "$UB_INSTALLDIR"/usr/lib32
fi
