#!/bin/sh -eux

ub_install

chmod -x "$UB_INSTALLDIR"/usr/share/applications/ecere.desktop
if [ -d "$UB_INSTALLDIR"/usr/lib32 ]; then
	cp -a "$UB_INSTALLDIR"/usr/lib32/*.* "$UB_INSTALLDIR"/usr/lib/;
	rm "$UB_INSTALLDIR"/usr/lib32/*.*
	rmdir "$UB_INSTALLDIR"/usr/lib32
fi
