#!/bin/sh -eux

if [ ! -f version ]; then
	echo "echo $UB_VERSION" > version
fi

# touch intltool-{extract,merge,update}.in

NOCONFIGURE=1 ./autogen.sh

# GData: libgdata 0.17.1, inkább 0.17.2

ub_compile \
    --enable-crash-dialog \
    --enable-alternate-addressbook \
    --disable-gtk3 \
    --disable-ldap \
    --disable-jpilot \
    --disable-bsfilter-plugin

# ub_make -C po claws-mail.pot update-po
