#!/bin/sh -eux

ub_replace sphinx-build sphinx-build2 configure.ac
ub_replace -O3 -O2 lib/prot.c
ub_replace -O3 -O2 lib/util.c
ub_replace -O3 -O2 Makefile.am
ub_replace -O3 -O2 imap/imapparse.c

rm -rf et
rm -rf syslog
autoreconf -vif

UB_MAKE_PROCS=1 \
ub_compile \
	--enable-murder \
	--with-com_err=/usr \
	--with-syslogfacility=MAIL
