#!/bin/sh -eux

cp -r "$UB_COMPILEDIR"/usr "$UB_INSTALLDIR"/

rm -Rf "$UB_INSTALLDIR"/usr/share/{lintian,menu}

mkdir -p "$UB_INSTALLDIR"/usr/lib/opera/
cp -r "$UB_INSTALLDIR"/usr/lib/i386-linux-gnu/opera "$UB_INSTALLDIR"/usr/lib/
rm -Rf "$UB_INSTALLDIR"/usr/lib/i386-linux-gnu

ln -sf /usr/lib/opera/opera "$UB_INSTALLDIR"/usr/bin/opera
