#!/bin/sh -eux

ub_install

mv "$UB_INSTALLDIR"/etc/stunnel/stunnel.conf{-sample,}

# fix foreign manpages
mkdir -p "$UB_INSTALLDIR"/usr/share/man/fr/man8
mv "$UB_INSTALLDIR"/usr/share/man/man8/stunnel.fr.8 "$UB_INSTALLDIR"/usr/share/man/fr/man8/stunnel.8
mkdir -p "$UB_INSTALLDIR"/usr/share/man/pl/man8
mv "$UB_INSTALLDIR"/usr/share/man/man8/stunnel.pl.8 "$UB_INSTALLDIR"/usr/share/man/pl/man8/stunnel.8

# systemd
cp -a tools/stunnel.service "$UB_INSTALLDIR"/usr/lib/systemd/system/
