#!/bin/sh -eux

cp      s "$UB_INSTALLDIR"/usr/bin/
chmod  +x "$UB_INSTALLDIR"/usr/bin/s

mkdir  -p "$UB_INSTALLDIR"/usr/lib/s
cp editor "$UB_INSTALLDIR"/usr/lib/s/
chmod  +x "$UB_INSTALLDIR"/usr/lib/s/editor
