#!/bin/sh -eux

mkdir build
cd build
cmake \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib \
	-DCMAKE_PREFIX_PATH=/usr/lib/qt5 \
	-DUSE_HDF5=ON \
	-DUSE_PROTOCALL=OFF \
	-DBUILD_GPL_PLUGINS=ON \
	-DUSE_MOLEQUEUE=ON\
	-DUSE_VTK=OFF\
	-DCMAKE_BUILD_TYPE=Release \
	..
sed s/-lQt5OpenGL//g -i avogadro/qtplugins/CMakeFiles/AvogadroQtPlugins.dir/link.txt
make
