#!/bin/sh -eux

ub_install

cp -a cppcheck.1 "$UB_INSTALLDIR"/usr/share/man/man1/cppcheck.1
cp -a gui/cppcheck-gui "$UB_INSTALLDIR"/usr/bin/
cp -a gui/icon.png "$UB_INSTALLDIR"/usr/share/pixmaps/cppcheck.png

for _f in cfg/*; do
	install -D -p -m 644 $_f "$UB_INSTALLDIR"/usr/share/cppcheck/$_f
done
