#!/bin/bash -eux

cp -r nouveau ${UB_INSTALLDIR}/lib/firmware/

# cd ../dvb-firmware
cp -a dvb-firmware/* ${UB_INSTALLDIR}/lib/firmware

cp tiacx*  "$UB_INSTALLDIR"/lib/firmware/

cp ipw2100/*.fw  "$UB_INSTALLDIR"/lib/firmware/

cp ipw2200/*.fw  "$UB_INSTALLDIR"/lib/firmware/

cp zd1211/zd1211* "$UB_INSTALLDIR"/lib/firmware/

chmod 755 ${UB_INSTALLDIR}/lib/firmware/b43{,legacy}
