#!/bin/bash -eux

cp -r nouveau ${UB_INSTALLDIR}/lib/firmware/

cd ./linux-firmware
export DESTDIR=${UB_INSTALLDIR}
ub_make install

cd ../dvb-firmware
cp -a * ${UB_INSTALLDIR}/lib/firmware

# cd ../broadcom-firmware
# cd ../lib/firmware
# cp -a b43 b43legacy ${UB_INSTALLDIR}/lib/firmware

chmod 755 ${UB_INSTALLDIR}/lib/firmware/b43{,legacy}

rm -f ${UB_INSTALLDIR}/lib/firmware/configure
rm -f ${UB_INSTALLDIR}/lib/firmware/Makefile

