#!/bin/sh -eux

install -d -m 777 "$UB_INSTALLDIR"/usr/lib/crafty

mv crafty "$UB_INSTALLDIR"/usr/lib/crafty/
mv book*.bin "$UB_INSTALLDIR"/usr/lib/crafty/
mv crafty.hlp "$UB_INSTALLDIR"/usr/lib/crafty/
