#!/bin/sh -eux

export CXXFLAGS='-std=gnu++98 -Wno-write-strings -fno-strict-aliasing -Wno-unused -Wno-unused-but-set-variable -Wno-unused-result -Wno-sign-compare -Wno-reorder'
cmake \
	-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG \
	-DCMAKE_CXX_FLAGS_DEBUG= \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DWITH_OPENGL=Y \
	-DDATADIR=share/games/vavoom\
	-DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config2 \
	-DWITH_SDL=Y \
	-DWITH_LIBMAD:BOOL=OFF \
	.
ub_make
