#!/bin/sh -eux

cd js/src
export SHELL=/bin/bash
rm -rf ctypes/libffi editline
ub_compile \
	--with-system-nspr \
	--enable-threadsafe \
	--enable-readline \
	--enable-jemalloc \
	--enable-system-ffi
