#!/bin/sh

. /etc/os-release

cat <<EOF
menuentry '$PRETTY_NAME i386' {
 linux /boot/bzImage.i386 boot=\$uhu_boot \$uhu_boot_options
 initrd /boot/initramfs.i386.cpio.gz
}
menuentry '$PRETTY_NAME x86_64' {
 linux /boot/bzImage.x86_64 boot=\$uhu_boot \$uhu_boot_options
 initrd /boot/initramfs.x86_64.cpio.gz
}
EOF
