#!/bin/bash -eux

#előkészület
KVER="$(ls -1 /lib/modules|grep i386)"
forras="NVIDIA-Linux-x86-${UB_VERSION}-pkg0"
moduldir="$UB_COMPILEDIR/lib/modules/"$KVER"/kernel/drivers"
mkdir -p $moduldir
unmakeself $forras.run
rm $forras.run
cd usr/share/applications
patch -i "$UB_SRCDIR"/patches/menu.patch.skip
cd ../../src/nv
patch -i "$UB_SRCDIR"/patches/nvidia_3.14_kernel.patch.skip
sed -i \
	-e 's:-Wpointer-arith::g' \
	-e 's:-Wsign-compare::g' \
	Makefile.kbuild

ln -s Makefile.kbuild Makefile
make SYSSRC=/usr/src/linux KERNEL_UNAME="$KVER" MODULE_ROOT=$moduldir module
sed -e 's/suser-sanity-check //g' -i Makefile.kbuild
sed -e 's/depmod -ae/true/g' -i Makefile.kbuild
make SYSSRC=/usr/src/linux KERNEL_UNAME="$KVER" MODULE_ROOT=$moduldir module-install
make clean
