#!/bin/bash -eux
#kernel verzió
KVER="$(ls -1 /lib/modules|grep i386)"
#célkönyvtárak
bindir="$UB_INSTALLDIR"/usr/bin
cellibdir="$UB_INSTALLDIR"/usr/lib
xmoduldir="$cellibdir"/xorg/modules
desktopdir="$UB_INSTALLDIR"/usr/share/applications
mandir="$UB_INSTALLDIR"/usr/share/man/man1/
pixmapdir="$UB_INSTALLDIR"/usr/share/pixmaps/
docdir="$UB_INSTALLDIR"/usr/share/doc/NVIDIA_GLX-1.0

mkdir -p "$cellibdir"/nvidia \
	"$xmoduldir"/{drivers,extensions} \
	"$desktopdir" \
	"$mandir" \
	"$pixmapdir" \
	"$bindir" \
	"$docdir"
# libek
mv lib $UB_INSTALLDIR/
cp -r usr/lib/* "$cellibdir"/
# man
install -m644 usr/share/man/man1/* $mandir/
rm $mandir/nvidia-installer.1.gz
# pixmap
mv usr/share/applications/nvidia-settings.desktop "$desktopdir"/
cp usr/share/pixmaps/nvidia-settings.png $pixmapdir/
# biztonságba helyezés a régi módon
mv usr/X11R6/lib/modules/extensions/libglx.so."$UB_VERSION" "$cellibdir"/nvidia/
# meghajtó modulok
mv usr/X11R6/lib/modules/drivers/nvidia_drv.so "$xmoduldir"/drivers/
mv usr/X11R6/lib/libXvMCNVIDIA.so."$UB_VERSION" "$cellibdir"/
mv usr/X11R6/lib/modules/libnvidia-wfb.so."$UB_VERSION" "$xmoduldir"/
# binek
install -m755 usr/bin/nvidia-{settings,xconfig,bug-report.sh} $bindir/
# doc
cp -r usr/share/doc/* "$docdir"/
rm "$docdir"/{Copyrights,NVIDIA_Changelog,README.txt}
# linkgyártások
cd "$cellibdir"
ln -s libGLcore.so."$UB_VERSION" libGLcore.so.1
ln -s libnvidia-cfg.so."$UB_VERSION" libnvidia-cfg.so.1
ln -s libnvidia-cfg.so.1 libnvidia-cfg.so
ln -s libnvidia-tls.so."$UB_VERSION" libnvidia-tls.so.1
ln -s libXvMCNVIDIA.so."$UB_VERSION" libXvMCNVIDIA_dynamic.so.1
ln -s libXvMCNVIDIA_dynamic.so.1 libXvMCNVIDIA_dynamic.so
cd tls
ln -s libnvidia-tls.so."$UB_VERSION" libnvidia-tls.so.1
cd "$xmoduldir"
ln -s libnvidia-wfb.so."$UB_VERSION" libnvidia-wfb.so.1
