#!/bin/sh -eux

python3 setup.py install --root="$UB_INSTALLDIR"
mv "$UB_INSTALLDIR"/usr/bin/django-admin.py "$UB_INSTALLDIR"/usr/bin/django-admin3.py

python setup.py install --root="$UB_INSTALLDIR"

mkdir -p "${UB_INSTALLDIR}"/usr/share/doc/django
cp -r docs/_build/html "${UB_INSTALLDIR}"/usr/share/doc/django/
