#!/bin/sh -eux

ub_install

mv doc/example .
rm -rf doc/rtf doc/guide.dvi doc/guide.lyx
mv doc/guide.info "$UB_INSTALLDIR"/usr/share/info/linuxdoc-tools.info
ln -s /usr/share/info/linuxdoc-tools.info doc/guide.info
mv doc guide

rm -rf "$UB_INSTALLDIR"/usr/share/doc/linuxdoc-tools
