#!/bin/sh -eux

#A nyomorult a compile fáztisban is installáll már!!
mkdir -p $UB_INSTALLDIR/usr/lib/vdr
mkdir -p $UB_INSTALLDIR/usr/share/locale

make  CONFDIR=/var/vdr/config \
	VIDEODIR=/var/vdr/video \
	DVBDIR=/usr/include/linux/dvb \
	LIBDIR=$UB_INSTALLDIR/usr/lib/vdr \
	LOCALEDIR=$UB_INSTALLDIR/usr/share/locale \
	DESTDIR=$UB_INSTALLDIR
