#!/bin/sh -eux

mkdir curses
cd curses
sh ../configure \
	--enable-32bit \
	--prefix=/usr \
	--mandir=/usr/share/man \
	--with-ncurses \
	--with-rexx=regina
make nthe

cd ..

#make clean
mkdir xcurses
cd xcurses
sh ../configure \
	--enable-32bit \
	--prefix=/usr \
	--mandir=/usr/share/man \
	--with-xcurses \
	--with-rexx=regina \
	--enable-force-utf8
make xthe

make THE_Help.txt
make the.man
cat the.man | gzip >the.man.gz
make combined

sed "s/Version 3.2/Version $UB_VERSION/" THE_Help.txt ../overview
