#!/bin/sh -eux

chmod +x install-sh

cd curses
ub_install
cd ..

cd xcurses
ub_install

mkdir -p "$UB_INSTALLDIR"/usr/share/THE
ln -sf xthe "$UB_INSTALLDIR"/usr/bin/the
ln -sf nthe "$UB_INSTALLDIR"/usr/bin/the-nox
chmod 644 ../plsql.tld
cp -a ../*.tld "$UB_INSTALLDIR"/usr/share/THE/
cp THE_Help.txt "$UB_INSTALLDIR"/usr/share/THE/
mkdir -p "$UB_INSTALLDIR"/usr/share/doc/the
cp -a ./doc/combined/THE-*.html "$UB_INSTALLDIR"/usr/share/doc/the/
cp -a the.man.gz "$UB_INSTALLDIR"/usr/share/doc/the/
chmod 644 ../images/the64.png
cp -a ../images/the64.png "$UB_INSTALLDIR"/usr/share/doc/the/
ln -sf ../doc/the/the64.png "$UB_INSTALLDIR"/usr/share/pixmaps/
ln -sf ../usr/share/THE/.therc "$UB_INSTALLDIR"/etc/.therc
