#!/bin/sh -eux

export QTDIR=/usr/lib/qt5

python3 configure.py --confirm-license \
	-w \
	-a \
	-q $QTDIR/bin/qmake \
	-s /usr/include/dbus-1.0 \
	-b /usr/bin \
	-d /usr/lib/python3.4/site-packages \
	--no-designer-plugin \
	--no-qsci-api \
	--no-qml-plugin \
	--no-sip-files

ub_make
