#!/bin/sh -eux

ub_install INSTALL_ROOT="$UB_INSTALLDIR"

mv ${UB_INSTALLDIR}/usr/bin/pyuic5 ${UB_INSTALLDIR}/usr/bin/pyuic5-python3
mv ${UB_INSTALLDIR}/usr/bin/pylupdate5 ${UB_INSTALLDIR}/usr/bin/pylupdate5-python3
mv ${UB_INSTALLDIR}/usr/bin/pyrcc5 ${UB_INSTALLDIR}/usr/bin/pyrcc5-python3
