#!/bin/sh -eux

sed 's%#define _IRR_OPENGL_USE_EXTPOINTER_%//#define _IRR_OPENGL_USE_EXTPOINTER_%' -i include/IrrCompileConfig.h
sed 's%INSTALL_DIR = /usr/local/lib%INSTALL_DIR = $(DESTDIR)/usr/lib%' -i source/Irrlicht/Makefile

cd source/Irrlicht
ub_make NDEBUG=1 sharedlib
ub_make NDEBUG=1 staticlib
