#!/bin/sh -eux

CC="ccache gcc -m32"
CXX="ccache g++ -m32"
export SHELL=/bin/bash
export LDFLAGS="-Wl,-rpath,/usr/lib/firefox/ -Wl,--no-keep-memory"

: > .mozconfig
cat > .mozconfig << _EOF_
ac_add_options --host='i686-uhu-linux'
ac_add_options --target='i686-uhu-linux'
ac_add_options --prefix=/usr
ac_add_options --enable-application=browser
ac_add_options --enable-official-branding
ac_add_options --enable-optimize="-O2"
ac_add_options --without-system-jpeg
ac_add_options --with-system-zlib
ac_add_options --with-pthreads
ac_add_options --with-system-icu
ac_add_options --with-system-nss
ac_add_options --with-system-nspr
ac_add_options --enable-gstreamer=1.0
ac_add_options --enable-system-cairo
ac_add_options --enable-system-sqlite
ac_add_options --enable-gio
ac_add_options --enable-pango
ac_add_options --enable-svg
ac_add_options --enable-canvas
ac_add_options --enable-xinerama
ac_add_options --enable-startup-notification
ac_add_options --enable-libxul
ac_add_options --disable-gconf
ac_add_options --disable-gnomeui
ac_add_options --disable-gnomevfs
ac_add_options --disable-installer
ac_add_options --disable-updater
ac_add_options --disable-crashreporter
ac_add_options --disable-tests
ac_add_options --disable-mochitest
ac_add_options --enable-default-toolkit=cairo-gtk2
ac_add_options --disable-necko-wifi
_EOF_

cd "$UB_OBJECTDIR"
"$UB_COMPILEDIR"/configure

ub_make

