#!/bin/sh -eux

# --disable-skia-gpu:
# gcc: include/c++/6.2.0/bits/unique_ptr.h:614:2: error: use of undeclared identifier 'swap'

if [ "$UB_ARCH" == "amd64" ];then
CC="ccache gcc -march=k8 -m64"
CXX="ccache g++ -march=k8 -m64"
else
CC="ccache gcc -m32"
CXX="ccache g++ -m32"
fi

export RUSTFLAGS="-Cdebuginfo=0"
export LDFLAGS="-Wl,-rpath,/usr/lib/firefox/ -Wl,--no-keep-memory -Wl,-z,relro -Wl,-z,now"

# libpng >= 1.6.35
# icu >= 63.1
# libvpx >= 1.7.0

: > .mozconfig
cat > .mozconfig << _EOF_
mk_add_options MOZ_OBJDIR=$UB_OBJECTDIR
ac_add_options --prefix=/usr
ac_add_options --enable-application=browser
ac_add_options --enable-release
ac_add_options --enable-official-branding
ac_add_options --enable-crashreporter
ac_add_options --enable-optimize=-O2
ac_add_options --with-system-bz2
ac_add_options --with-system-nss
ac_add_options --with-system-nspr
ac_add_options --with-system-zlib
ac_add_options --without-system-icu
ac_add_options --without-system-jpeg
ac_add_options --without-system-libevent
ac_add_options --without-system-libvpx
ac_add_options --without-system-png
ac_add_options --enable-system-sqlite
ac_add_options --enable-startup-notification
ac_add_options --enable-default-toolkit=cairo-gtk3-wayland
ac_add_options --enable-bundled-fonts
ac_add_options --disable-clang-plugin
ac_add_options --disable-debug
ac_add_options --disable-gconf
ac_add_options --disable-necko-wifi
ac_add_options --disable-skia-gpu
ac_add_options --disable-updater
ac_add_options --disable-tests
ac_add_options --disable-strip
ac_add_options --disable-install-strip
ac_add_options --disable-elf-hack
_EOF_

if [ "$UB_ARCH" == "amd64" ];then
echo "ac_add_options --host=x86_64-linux-gnu" >> .mozconfig
echo "ac_add_options --target=x86_64-linux-gnu" >> .mozconfig
else
echo "ac_add_options --host=i686-linux-gnu" >> .mozconfig
echo "ac_add_options --target=i686-linux-gnu" >> .mozconfig
fi

# cd "$UB_OBJECTDIR"

# az UB_CONFIGURE_DIR="$UB_COMPILEDIR" forma nem jó, linker hiba lesz belőle
# "$UB_COMPILEDIR"/configure

# ub_make

"$UB_COMPILEDIR"/mach build
