#!/bin/sh -eux

cd "$UB_OBJECTDIR"

ub_install

cp "$UB_COMPILEDIR"/browser/branding/official/default48.png "$UB_INSTALLDIR"/usr/share/pixmaps/firefox.png

rm -f "$UB_INSTALLDIR"/usr/lib/firefox/firefox
rm -f "$UB_INSTALLDIR"/usr/bin/firefox
ln -s /usr/lib/firefox/firefox "$UB_INSTALLDIR"/usr/bin/firefox

ln -s firefox "$UB_INSTALLDIR"/usr/lib/firefox-"$UB_VERSION"
ln -s firefox-devel "$UB_INSTALLDIR"/usr/lib/firefox-devel-"$UB_VERSION"
ln -s firefox-"$UB_VERSION" "$UB_INSTALLDIR"/usr/include/firefox
ln -s firefox-"$UB_VERSION" "$UB_INSTALLDIR"/usr/share/idl/firefox

mkdir -p "$UB_INSTALLDIR"/usr/lib/firefox/browser/extensions/langpack-hu@firefox.mozilla.org
cp -aR "$UB_COMPILEDIR"/langpack-hu/. "$UB_INSTALLDIR"/usr/lib/firefox/browser/extensions/langpack-hu@firefox.mozilla.org/
