#!/bin/sh -eux

ub_install

mv "$UB_INSTALLDIR"/usr/bin/{d2x-sdl,descent2}

mkdir -p "$UB_INSTALLDIR"/usr/share/games/descent2
rm d2shar10/*.{bat,exe,lst,386}
cp -a d2shar10/. "$UB_INSTALLDIR"/usr/share/games/descent2/
