#!/bin/sh -eux

export PATH=/usr/lib/qt4/bin:"$PATH"
export QTDIR=/usr/lib/qt4

cd Qt4Qt5
qmake qscintilla.pro
sed -i 's/INSTALL_ROOT/UB_INSTALLDIR/g' Makefile

ub_make

ub_install

cp *.h "$UB_INSTALLDIR"/usr/lib/qt4/include

# python stuff
cd ../Python

python configure.py \
	--qsci-incdir="$UB_INSTALLDIR"/usr/lib/qt4/include \
	--qsci-libdir="$UB_INSTALLDIR"/usr/lib/qt4/lib \

sed -i 's/INSTALL_ROOT/UB_INSTALLDIR/g' Makefile

ub_make
