#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/jgrasp/bin/linux
cp -a bin/linux/jgrasp "$UB_INSTALLDIR"/usr/share/jgrasp/bin/linux/
cp -a bin/jgrasp "$UB_INSTALLDIR"/usr/share/jgrasp/bin/
install -m644 jgrasp.jar "$UB_INSTALLDIR"/usr/share/jgrasp/

mkdir -p "$UB_INSTALLDIR"/usr/share/jgrasp/data
install -m644 data/* "$UB_INSTALLDIR"/usr/share/jgrasp/data/

mkdir -p "$UB_INSTALLDIR"/usr/share/jgrasp/help
install -m644 help/* "$UB_INSTALLDIR"/usr/share/jgrasp/help/

mkdir -p "$UB_INSTALLDIR"/usr/share/jgrasp/jbin
install -m644 jbin/*.class "$UB_INSTALLDIR"/usr/share/jgrasp/jbin/
install -m755 jbin/linux_run "$UB_INSTALLDIR"/usr/share/jgrasp/jbin/

install -d -m755 "$UB_INSTALLDIR"/usr/share/jgrasp/examples/Tutorials/Hello
install -d -m755 "$UB_INSTALLDIR"/usr/share/jgrasp/examples/Tutorials/PersonalLibrary/PersonalLibrary_doc/resources
install -d -m755 "$UB_INSTALLDIR"/usr/share/jgrasp/examples/Tutorials/ViewerExamples/jgraspvex
install -m644 examples/*.* "$UB_INSTALLDIR"/usr/share/jgrasp/examples/
install -m644 examples/Tutorials/*.* "$UB_INSTALLDIR"/usr/share/jgrasp/examples/Tutorials/
install -m644 examples/Tutorials/Hello/*.* "$UB_INSTALLDIR"/usr/share/jgrasp/examples/Tutorials/Hello/
install -m644 examples/Tutorials/PersonalLibrary/*.* "$UB_INSTALLDIR"/usr/share/jgrasp/examples/Tutorials/PersonalLibrary/
install -m644 examples/Tutorials/PersonalLibrary/PersonalLibrary_doc/*.* \
	"$UB_INSTALLDIR"/usr/share/jgrasp/examples/Tutorials/PersonalLibrary/PersonalLibrary_doc/
install -m644 examples/Tutorials/PersonalLibrary/PersonalLibrary_doc/resources/*.* \
	"$UB_INSTALLDIR"/usr/share/jgrasp/examples/Tutorials/PersonalLibrary/PersonalLibrary_doc/resources/
install -m644 examples/Tutorials/ViewerExamples/*.* "$UB_INSTALLDIR"/usr/share/jgrasp/examples/Tutorials/ViewerExamples/
install -m644 examples/Tutorials/ViewerExamples/jgraspvex/*.* \
	"$UB_INSTALLDIR"/usr/share/jgrasp/examples/Tutorials/ViewerExamples/jgraspvex/

install -d -m755 "$UB_INSTALLDIR"/usr/share/jgrasp/extensions/classes/cs1
install -d -m755 "$UB_INSTALLDIR"/usr/share/jgrasp/extensions/viewers
install -d -m755 "$UB_INSTALLDIR"/usr/share/jgrasp/extensions/tools
install -m644 extensions/classes/*.* "$UB_INSTALLDIR"/usr/share/jgrasp/extensions/classes/
install -m644 extensions/classes/cs1/*.* "$UB_INSTALLDIR"/usr/share/jgrasp/extensions/classes/cs1/
install -m644 extensions/tools/*.* "$UB_INSTALLDIR"/usr/share/jgrasp/extensions/tools/
install -m644 extensions/viewers/*.* "$UB_INSTALLDIR"/usr/share/jgrasp/extensions/viewers/

ln -s ../share/jgrasp/bin/jgrasp "$UB_INSTALLDIR"/usr/bin/jgrasp
