#!/bin/sh -eux

ub_install
chmod +x ${UB_INSTALLDIR}/usr/share/mesa-demos/bin/*
mv ${UB_INSTALLDIR}/usr/share/mesa-demos/bin/{es2_info,glinfo,glxgears,glxinfo,pbinfo} ${UB_INSTALLDIR}/usr/bin/
mkdir -p ${UB_INSTALLDIR}/usr/share/pixmaps
mv icon.png ${UB_INSTALLDIR}/usr/share/pixmaps/mesa-demos.png
