#!/bin/sh -eux

ub_install

ln -sf libmysqlclient.so.18 "$UB_INSTALLDIR"/usr/lib/libmysqlclient_r.so.18
ln -sf libmysqlclient.so.18.0.0 "$UB_INSTALLDIR"/usr/lib/libmysqlclient_r.so.18.0.0
ln -sf mariadb.pc "$UB_INSTALLDIR"/usr/lib/pkgconfig/mysql.pc
