#!/bin/sh -eux

# texturepacker cannot build statically
sed '/--enable-static/d' -i tools/depends/native/TexturePacker/Makefile

export JAVA=/usr/lib/java/jre/bin/java
./bootstrap
export JAVA_EXE=/usr/lib/java/jre/bin/java
export ac_cv_path_LATEX=no
export ac_cv_lib_avcodec_ff_vdpau_vc1_decode_picture=yes
ub_compile \
	--enable-libbluray \
	--enable-pulse \
	--enable-sdl \
	--enable-gl \
	--enable-goom \
	--enable-udev \
	--enable-vaapi \
	--enable-vdpau \
	--disable-debug \
	--enable-xrandr \
	--enable-texturepacker \
	--enable-joystick \
	--enable-rsxs \
	--enable-projectm \
	--enable-x11 \
	--enable-samba \
	--enable-nfs \
	--enable-airplay \
	--enable-dvdcss \
	--enable-avahi \
	--enable-webserver \
	--enable-optical-drive \
	--with-ffmpeg-shared
# --with-ffmpeg=shared - ffmpeg 2.4.4 kellene
# --enable-libusb - udev esetén nem kell, így mindenképp letiltja
