#!/bin/sh -eux

ub_install

mkdir -p "$UB_INSTALLDIR"/usr/share/doc/Packages/flac
mv -f "$UB_INSTALLDIR"/usr/share/doc/flac-"$UB_VERSION"/html "$UB_INSTALLDIR"/usr/share/doc/Packages/flac
mv -f "$UB_INSTALLDIR"/usr/share/doc/flac-"$UB_VERSION"/FLAC.tag "$UB_INSTALLDIR"/usr/share/doc/Packages/flac
rmdir "$UB_INSTALLDIR"/usr/share/doc/flac-"$UB_VERSION"/
