#!/bin/sh -eux

autoreconf -vfi -I m4
export LINGUAS="`ls po/*.po | sed 's:po/\(.*\)\.po$:\1:'`"
ub_compile \
	--enable-usermenu \
	--with-nlsdir=/usr/share/locale \
	--with-pixmapdir=/usr/share/pixmaps \
	--with-x \
	--enable-xpm \
	--enable-png \
	--enable-jpeg \
	--enable-gif \
	--enable-tiff \
	--enable-xrandr \
	--enable-xinerama \
	--enable-modelock

cd windowmaker-extra

ub_compile
