#!/bin/sh -eux

#	-Denable_google_now=0
#	-Denable_hotwording=0
#   -Drelease_extra_cflags=" -fno-delete-null-pointer-checks"
#	-Dcomponent="shared_library"

_google_api_key=AIzaSyDwr302FpOSkGRpLlUpPThNTDPbXcIn_FM
_google_default_client_id=413772536636.apps.googleusercontent.com
_google_default_client_secret=0ZChLK6AxeA3Isu96MkwqDR4

_flags=("
is_debug=false
is_clang=false
clang_use_chrome_plugins=false
linux_use_bundled_binutils=false
fatal_linker_warnings=false
treat_warnings_as_errors=false
fieldtrial_testing_like_official_build=false
use_sysroot=false
use_gold=false
use_allocator=\"none\"
enable_nacl=false
enable_nacl_nonsfi=false
enable_widevine=false
enable_hangout_services_extension=false
ffmpeg_branding=\"Chrome\"
proprietary_codecs=true
remove_webcore_debug_symbols=true
google_api_key=\"${_google_api_key}\"
google_default_client_id=\"${_google_default_client_id}\"
google_default_client_secret=\"${_google_default_client_secret}\"
use_cups=true
use_gconf=false
use_gio=false
use_gnome_keyring=false
use_gtk3=false
use_kerberos=false
use_nss_certs=true
use_pulseaudio=true
link_pulseaudio=true
")

_syslibs=(
#	ffmpeg
	flac
	harfbuzz-ng
	icu
	libevent
#	libjpeg (linker error)
#	libpng (linker error)
	libvpx
	libwebp
	libxml
	libxslt
#	re2
#	snappy
	yasm
#	zlib (linker error)
)

sed "s|//third_party/usb_ids/usb.ids|/usr/share/hwdata/usb.ids|g" -i device/usb/BUILD.gn

build/linux/unbundle/replace_gn_files.py --system-libraries "${_syslibs[@]}"

export LDFLAGS+="-Wl,-rpath,/usr/lib/chromium/ -Wl,--no-keep-memory"

# gn a buildhoz, először simán gcc-vel, utána önmagával
# a --gn-gen-args utáni sorok nem kezdőshetnek tab karakterrel!
tools/gn/bootstrap/bootstrap.py -v --gn-gen-args " ${_flags[@]} "

# build chrome: az --args utáni sorok nem kezdőshetnek tab karakterrel!
out/Release/gn gen out/Release -v --script-executable=/usr/bin/python2 \
	--args=" ${_flags[@]} "

# ninja, a 34-től a make nem támogatott

LC_ALL=C ninja -C out/Release -v pdf chrome chrome_sandbox chromedriver
