#!/bin/sh -eux

# ninja.
# a 34.0.1847.131 valamiért csak ezzel fordul le rendesen,
# make használatánál linker hibák lesznek.

unzip ninja.zip
cd ninja-1.4.0
./bootstrap.py --verbose
cd ..
rm -f ninja.zip

# ok, chromium

export LDFLAGS+="-Wl,-rpath,/usr/lib/chromium/ -Wl,--no-keep-memory"

build/gyp_chromium -f ninja build/all.gyp --no-parallel --depth=. \
	-Dhost_arch=ia32 \
	-Dtarget_arch=ia32 \
	-Dfastbuild=1 \
	-Dcomponent="shared_library" \
	-Dpython_ver="2.7" \
	-Dwerror= \
	-Dno_strict_aliasing=1 \
	-Ddisable_sse2=1 \
	-Dno_gc_sections=1 \
	-Drelease_optimize=2 \
	-Dlinux_strip_binary=1 \
	-Dlinux_use_gold_binary=0 \
	-Dlinux_use_gold_flags=0 \
	-Ddisable_nacl=1 \
	-Ddisable_pnacl=1 \
	-Denable_google_now=0 \
	-Dffmpeg_branding=Chrome \
	-Dlinux_sandbox_path=/usr/lib/chromium/chrome_sandbox \
	-Dtoolkit_wiews=0 \
	-Dtoolkit_uses_gtk=1 \
	-Duse_gnome_keyring=0 \
	-Duse_gconf=0 \
	-Duse_gio=1 \
	-Duse_system_ffmpeg=0 \
	-Duse_system_libjpeg=1 \
	-Duse_system_libxml=1 \
	-Duse_system_libxslt=1 \
	-Duse_system_ssl=0 \
	-Duse_system_sqlite=0 \
	-Duse_system_yasm=1

ninja-1.4.0/ninja -C out/Release chrome chrome_sandbox

