#!/bin/sh -eux

cp -a telepathy-qt telepathy-qt4
#qt5 verzió
cd telepathy-qt
ub_compile \
	-DCMAKE_PREFIX_PATH=/usr/lib/qt5 \
	-DDESIRED_QT_VERSION=5 \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DENABLE_EXAMPLES=OFF \
	-DENABLE_TESTS=OFF
#qt4 verzió
cd ../telepathy-qt4
ub_compile \
	-DDESIRED_QT_VERSION=4 \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DENABLE_EXAMPLES=OFF \
	-DENABLE_TESTS=OFF
