#!/bin/sh -eux

autoconf --force

AM_VER=`automake --version | head -n 1 | cut -d' ' -f4 | cut -d. -f-2`

cp /usr/share/automake-"$AM_VER"/config.guess "$UB_COMPILEDIR"/buildlib/config.guess
cp /usr/share/automake-"$AM_VER"/config.sub "$UB_COMPILEDIR"/buildlib/config.sub
cp /usr/share/automake-"$AM_VER"/config.sub "$UB_COMPILEDIR"/buildlib/config.rpath

cd "$UB_OBJECTDIR"

export CPPFLAGS='-std=c++11'

UB_CONFIGURE_DIR="$UB_COMPILEDIR" ub_configure
ub_make
