#!/bin/sh -eux

cd "$UB_OBJECTDIR"

mkdir -p "$UB_INSTALLDIR"/usr/include/apt-pkg
mkdir -p "$UB_INSTALLDIR"/usr/lib/apt/methods
mkdir -p "$UB_INSTALLDIR"/usr/lib/dpkg/methods/apt

cp -a bin/apt-*                  "$UB_INSTALLDIR"/usr/bin/
cp -a bin/libapt*                "$UB_INSTALLDIR"/usr/lib/
cp -a include/apt-pkg/.          "$UB_INSTALLDIR"/usr/include/apt-pkg/
cp -a bin/methods/.              "$UB_INSTALLDIR"/usr/lib/apt/methods/
cp -a scripts/dselect/.          "$UB_INSTALLDIR"/usr/lib/dpkg/methods/apt/

for i in "$UB_COMPILEDIR"/doc/en/*.[1-8]; do
	base="${i##*/}"
	ext="${base##*.}"
	mkdir -p "$UB_INSTALLDIR/usr/share/man/man$ext"
	mv "$i" "$UB_INSTALLDIR/usr/share/man/man$ext/"
done

rm -rf "$UB_INSTALLDIR"/usr/share/locale
mv locale "$UB_INSTALLDIR"/usr/share/
