#!/bin/sh -eux

ub_compile \
	--enable-udev_sync \
	--enable-udev_rules \
	--enable-fsadm \
	--enable-cmdlib \
	--enable-dmeventd \
	--libdir=/lib \
	--sbindir=/sbin \
	--with-clvmd=all \
	--enable-pkgconfig \
	--enable-applib \
	--enable-python-bindings \
	--enable-lvmetad
