#!/bin/sh -eux

rm -rf "$UB_INSTALLDIR"/usr/lib
mkdir -p "$UB_INSTALLDIR"/usr/lib
mv build/lib/obj/gcc/so{,_g,_stlg}/libstlport*.so* "$UB_INSTALLDIR"/usr/lib/
rm -rf "$UB_INSTALLDIR"/usr/include/stlport
mv stlport "$UB_INSTALLDIR"/usr/include/
