#!/bin/sh -eux

ub_configure \
	--enable-threads \
	--enable-xinerama \
	--enable-xft \
	--enable-xdbe \
	--enable-largefile \
	--enable-localpng \
	--libdir=/usr/lib/fltk1 \
	--libexecdir=/usr/lib/fltk1 \
	--includedir=/usr/include/fltk1
ub_make

cd test

ub_make blocks
ub_make sudoku
ub_make checkers
ub_make all

cd ../documentation
ub_make alldocs
