#!/bin/sh -eux

install -d "$UB_INSTALLDIR"/usr/share/scala/{bin,lib}
install -m 644 man/man1/*.1 "$UB_INSTALLDIR"/usr/share/man/man1
cp -a doc "$UB_INSTALLDIR"/usr/share/scala/
cp -a lib "$UB_INSTALLDIR"/usr/share/scala/
#cp -a misc "$UB_INSTALLDIR"/usr/share/scala/

for file in `ls bin` ; do
  if [[ -f bin/$file ]] && [[ -x bin/$file ]] ; then
    install -m 755 bin/$file "$UB_INSTALLDIR"/usr/share/scala/bin
    ln -s ../share/scala/bin/$file "$UB_INSTALLDIR"/usr/bin/$file
  fi
done
