#!/bin/sh -eux

sysarch=$(uname -m)

if [ "$UB_ARCH" == "amd64" ]; then
	export CTARGET="x86_64-uhu-linux"
	export CHOST="$sysarch-uhu-linux"
	export CBUILD="$sysarch-uhu-linux"
else
	export CTARGET="i686-uhu-linux"
	export CHOST="$sysarch-uhu-linux"
	export CBUILD="$sysarch-uhu-linux"
fi

cd build/workspaces
./update-workspaces.sh \
	--bindir=/usr/bin \
    --libdir=/usr/lib/0ad \
    --datadir=/usr/share/0ad/data

cd gcc
ub_make
