#!/bin/sh -eux

sysarch=$(uname -m)
if [ "$(dpkg --print-architecture)" == "i386" ];then
buildsys="i686"
else
buildsys="x86_64"
fi

if [ "$UB_ARCH" == "amd64" ]; then
	export CTARGET="x86_64-gnu-linux"
	export CHOST="$buildsys-gnu-linux"
	export CBUILD="$buildsys-gnu-linux"
else
	export CTARGET="i686-gnu-linux"
	export CHOST="$buildsys-gnu-linux"
	export CBUILD="$buildsys-gnu-linux"
fi

cd build/workspaces
./update-workspaces.sh \
	--bindir=/usr/bin \
    --libdir=/usr/lib/0ad \
    --datadir=/usr/share/0ad/data

cd gcc
ub_make
