#!/bin/sh -eux

export WX_CONFIG=/usr/bin/wx-config2
export SHELL=/bin/bash

cd build/workspaces
./update-workspaces.sh \
      --bindir=/usr/bin \
      --libdir=/usr/lib/0ad \
      --datadir=/usr/share/0ad/data
cd gcc
ub_make
