#!/bin/sh -eux

ub_install

install -Dm644 examples/tmux.vim "$UB_INSTALLDIR"/usr/share/vim/vimfiles/syntax/tmux.vim
install -dm755 "$UB_INSTALLDIR"/usr/share/tmux/
install -m644 examples/* "$UB_INSTALLDIR"/usr/share/tmux/
mkdir -p "$UB_INSTALLDIR"/etc/bash_completion.d
ln -s ../../usr/share/tmux/bash_completion_tmux.sh "$UB_INSTALLDIR"/etc/bash_completion.d/tmux
