#!/bin/sh -eux

mkdir build
cd build
UB_CONFIGURE_DIR=../ ub_configure \
	--disable-native-texlive-build \
	--with-banner-add=/UHU-Linux \
	--with-system-icu \
	--with-system-poppler \
	--with-system-freetype2 \
	--with-system-libpng \
	--with-system-zlib \
	--with-x \
	--enable-luatex \
	--disable-psutils \
	--disable-t1utils

ub_make
