#!/bin/sh -eux

# install texmf
cp -a texmf "$UB_INSTALLDIR"/usr/share/
cp -a texmf-dist "$UB_INSTALLDIR"/usr/share/

cd build
ub_install

sed -i 's/^TEXMFROOT = .*$/TEXMFROOT = $SELFAUTODIR\/share/' "$UB_INSTALLDIR"/usr/share/texmf/web2c/texmf.cnf
ln -s pdftex "$UB_INSTALLDIR"/usr/bin/latex

# install perl module
cd ..
mkdir -p "$UB_INSTALLDIR"/usr/share/tlpkg/TeXLive
install -m644 utils/biber/TeXLive/*.pm "$UB_INSTALLDIR"/usr/share/tlpkg/TeXLive

# remove execute bit
chmod -x "$UB_INSTALLDIR"/usr/share/texmf-dist/doc/bibtex/urlbst/urlbst.in

rm "$UB_INSTALLDIR"/usr/bin/man
rm "$UB_INSTALLDIR"/usr/bin/latexmk
rm "$UB_INSTALLDIR"/usr/bin/otfinfo
