#!/bin/sh -eux

for i in "install install-linux-shortcuts install-linux-mime install-linux-appdata install-man-page";do
    make \
        prefix=/usr \
        DESTDIR=${UB_INSTALLDIR} \
        $i
done
