#!/bin/sh -eux

DESTDIR="$UB_INSTALLDIR" \
ub_compile \
	--prefix=/var/lib/sympa \
	--sbindir=/usr/sbin \
	--sysconfdir=/etc/sympa \
	--libexecdir=/usr/lib/sympa/libexec \
	--datadir=/usr/share/sympa/default \
	--with-confdir=/etc \
	--with-cgidir=/srv/www/fcgi-bin/sympa \
	--with-iconsdir=/srv/www/html/sympa/icons \
	--with-modulesdir=/usr/lib/sympa/lib \
	--with-expldir=/var/lib/sympa/expl \
	--with-lockdir=/var/lock/sympa \
	--with-piddir=/var/run/sympa \
	--with-localedir=/usr/share/locale \
	--with-docdir=/usr/share/doc/Packages/sympa \
	--with-scriptdir=/usr/lib/sympa/bin \
	--with-spooldir=/var/spool/sympa \
	--with-aliases_file=/etc/aliases \
	--enable-secure
