#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/{chmsee,applications,pixmaps}

cp -a * "$UB_INSTALLDIR"/usr/share/chmsee
rm -rf "$UB_INSTALLDIR"/usr/share/chmsee/src
mv "$UB_INSTALLDIR"/usr/share/chmsee/data/chmsee.desktop.in "$UB_INSTALLDIR"/usr/share/applications/chmsee.desktop
sed -i 's/_//g' "$UB_INSTALLDIR"/usr/share/applications/chmsee.desktop
mv "$UB_INSTALLDIR"/usr/share/chmsee/data/chmsee-icon.png "$UB_INSTALLDIR"/usr/share/pixmaps/
