#!/bin/sh -eux

libtoolize --force --copy
autopoint --force
intltoolize --force --copy --automake
gnome-doc-prepare --force --copy
aclocal -I m4
autoconf
autoheader
touch config.h.in
automake --gnu --add-missing --force --copy -Wno-portability
ub_compile
