#!/bin/sh -eux

if [ "$UB_ARCH" == "i386" ];then
    sharedir="$UB_INSTALLDIR"/usr/share
    datadir="$sharedir"/games/zaxxon
    pixmapdir=$sharedir/pixmaps
    docdir=$sharedir/doc/Packages/zaxxon
    mkdir -p $datadir $pixmapdir $docdir
    chmod 0777 "$datadir"
    install --mode=644  *.dat $datadir/
    install --mode=755 zaxrr $datadir/
    cp zax80x80.png $pixmapdir/zaxxon.png
    # doc
    cp changelog.html floor.png readme.html zax80x80.png $docdir/
    #desktop
    desktopfile=$UB_INSTALLDIR/usr/share/applications/zaxxon.desktop
    echo [Desktop Entry] >> $desktopfile
    echo Name=zaxxon >> $desktopfile
    echo Type=Application >> $desktopfile
    echo Exec=zaxxon >> $desktopfile
    echo Icon=zaxxon >> $desktopfile
    echo 'Categories=Game;ArcadeGame;' >> $desktopfile
    # indító
    binfile=$UB_INSTALLDIR/usr/bin/zaxxon
    echo '#!/bin/bash' >> $binfile
    echo cd /usr/share/games/zaxxon >> $binfile
    echo padsp ./zaxrr '"$@"' >> $binfile
    chmod +x $binfile
else
rm $UB_SRCDIR/packages/zaxxon/depends
touch $UB_SRCDIR/packages/zaxxon/depends
fi
