#!/bin/sh -eux

cp -r FreeImage FreeImagefip
cd FreeImage
export CFLAGS+=" -O3 -fPIC -fexceptions -fvisibility=hidden -DNO_LCMS"
export CXXFLAGS+=" -O3 -fPIC -fexceptions -fvisibility=hidden -Wno-ctor-dtor-privacy"
ub_make
cd ../FreeImagefip
make -f Makefile.fip
