#!/bin/sh -eux

mkdir build
cd build
../bootstrap \
	--system-libs \
	--no-system-jsoncpp \
	--no-system-libuv \
	--prefix=/usr \
	--datadir=/share/cmake \
	--mandir=/share/man \
	--docdir=/share/doc/Packages/cmake

ub_make
