#!/bin/sh -eux

autoreconf -fi
ub_configure \
	--enable-texture-float \
	--enable-gles1 \
	--enable-gles2 \
	--enable-xorg \
	--enable-xa \
	--enable-xvmc \
	--enable-vdpau \
	--enable-osmesa \
	--enable-gbm \
	--enable-glx-tls \
	--enable-dri \
	--enable-glx \
	--enable-gallium-llvm \
	--enable-egl \
	--enable-gallium-egl \
	--with-egl-platforms=x11,drm \
	--enable-shared-glapi \
	--with-gallium-drivers=i915,ilo,nouveau,r300,r600,radeonsi,svga,swrast \
	--with-dri-drivers=i915,i965,r200,radeon,nouveau,swrast \
	--enable-r600-llvm-compiler
ub_make
