#!/bin/sh -eux

autoreconf -fi

ub_compile \
	--enable-texture-float \
	--enable-gles1 \
	--enable-gles2 \
	--enable-xa \
	--enable-xvmc \
	--enable-vdpau \
	--enable-osmesa \
	--enable-gbm \
	--enable-glx-tls \
	--enable-dri \
	--enable-glx \
	--enable-gallium-llvm \
	--enable-egl \
	--with-egl-platforms=x11,drm,wayland \
	--enable-shared-glapi \
	--with-gallium-drivers=i915,ilo,nouveau,r300,r600,radeonsi,svga,swrast \
	--with-dri-drivers=i915,i965,r200,radeon,nouveau,swrast \
	--enable-omx \
	--enable-nine \
	--enable-opencl \
	--enable-opencl-icd
