#!/bin/bash -eux

if [ "$UB_ARCH" == "amd64" ];then
	KVER="$(ls -1 /lib/modules | grep x86_64)"
else
	KVER="$(ls -1 /lib/modules | grep i386)"
fi

#célkönyvtárak
moduldir="$UB_INSTALLDIR"/lib/modules/"$KVER"/kernel/drivers
cellibdir="$UB_INSTALLDIR"/usr/lib
xmoduldir="$cellibdir"/xorg/modules
desktopdir="$UB_INSTALLDIR"/usr/share/applications
mandir="$UB_INSTALLDIR"/usr/share/man/man1/
vendordir="$UB_INSTALLDIR"/etc/OpenCL/vendors
pixmapdir="$UB_INSTALLDIR"/usr/share/pixmaps/

#könyvtárgyártás
mkdir -p "$cellibdir"/nvidia \
	"$moduldir" \
	"$xmoduldir"/{drivers,extensions} \
	"$desktopdir" \
	"$mandir" \
	"$vendordir" \
	"$pixmapdir"

#kernelmodulok
cp kernel/nvidia.ko "$moduldir"/

# binárisok
mv	nvidia-xconfig \
	nvidia-settings \
	nvidia-bug-report.sh \
	nvidia-smi \
	tls_test \
	tls_test_dso.so \
	"$UB_INSTALLDIR"/usr/bin/

# desktop
mv	nvidia-settings.desktop "$desktopdir"/
mv	nvidia-settings.png "$pixmapdir"/

# man
gunzip	*.1.gz
mv	*.1 "$mandir"/

# vendor
mv	nvidia.icd "$vendordir"/

# biztonságba helyezés a régi módon
mv	libglx.so."$UB_VERSION" "$cellibdir"/nvidia/

#Áthelyezzük a nem a $cellibdir alá kerülő *.so-kat
mv	nvidia_drv.so "$xmoduldir"/drivers/
mv	tls "$cellibdir"

# remove conflicting vdpau lib
###Jó nekünk az!
#rm "libvdpau.so.$UB_VERSION"
#rm "libvdpau_trace.so.$UB_VERSION"

# minden áthelyezése a libekbe
mv *.so.* "$cellibdir"/

# remove conflicting mesa lib
rm -f "$cellibdir"/libGLESv2.so.2

#linkgyártások
cd "$cellibdir"
ln -s libwfb.so xorg/modules/libnvidia-wfb.so."$UB_VERSION"
ln -s "libvdpau_nvidia.so.$UB_VERSION" libvdpau_nvidia.so
ln -s "libnvcuvid.so.$UB_VERSION" libnvcuvid.so.1
ln -s libnvcuvid.so.1 libnvcuvid.so
ln -s "libcuda.so.$UB_VERSION" libcuda.so
