#!/bin/sh -eux

ub_install

install -Dm644 makefiles/unix/man/smc.6 "$UB_INSTALLDIR"/usr/share/man/man6/smc.6
install -Dm644 makefiles/unix/smc.xpm "$UB_INSTALLDIR"/usr/share/pixmaps/smc.xpm
install -Dm644 makefiles/unix/smc.desktop "$UB_INSTALLDIR"/usr/share/applications/smc.desktop
  
find "$UB_INSTALLDIR"/usr/share -iname '*.po' -delete
rm -Rf "$UB_INSTALLDIR"/usr/share/smc/translations/pt_BR
