#!/bin/sh -eux

ub_install
mv $UB_INSTALLDIR/usr/share/desktop-directories/accessories.desktop \
  $UB_INSTALLDIR/usr/share/desktop-directories/accessories.directory
mkdir -p $UB_INSTALLDIR/usr/share/icons/jsm
cp $UB_INSTALLDIR/usr/usr/share/icons/jsm/* $UB_INSTALLDIR/usr/share/icons/jsm
rm -rf $UB_INSTALLDIR/usr/usr
