#!/bin/sh -eux

rm -rf mcs/class/lib/monolite/*
export UB_MAKE_PROCS=1
export CFLAGS="-fno-strict-aliasing"
ub_compile \
	--with-sgen=no \
	--with-libgdiplus=yes \
	--with-jit=yes \
	--with-ikvm-native=yes \
	--disable-system-aot
