#!/bin/sh -eux

./configure \
	--prefix=/usr \
	--enable-ccache \
	--enable-shared \
	--enable-runtime-cpu-detect \
	--enable-postproc \
    --enable-pic \
    --enable-vp8 \
    --enable-vp9 \
    --enable-vp9-highbitdepth \
    --enable-spatial-svc \
    --disable-install-docs \
    --disable-install-srcs
ub_make
