#!/bin/sh -eux

for i in col colcrt colrm column hexdump look ncal ul write ; do
	rm -rf usr.bin/"$i"/* ; rmdir usr.bin/"$i" ;
	rm -rf debian/patches/"$i"* ;
done

rm -rf debian/patches/hd.diff
rm -rf debian/patches/libcalendar.diff
rm -rf debian/patches/series

for i in debian/patches/* ; do patch -Np1 < "$i" ; done

ub_compile
