#!/bin/sh -eux

ub_install

mkdir -p "$UB_INSTALLDIR"/usr/share/calendar
mkdir -p "$UB_INSTALLDIR"/etc/calendar
cp -a debian/calendars/calendar.* "$UB_INSTALLDIR"/usr/share/calendar/
cp -a debian/calendars/default "$UB_INSTALLDIR"/etc/calendar/
cp -a usr.bin/calendar/calendars/. "$UB_INSTALLDIR"/usr/share/calendar/
ln -s de_DE.ISO8859-1 "$UB_INSTALLDIR"/usr/share/calendar/de_DE
ln -s fr_FR.ISO8859-1 "$UB_INSTALLDIR"/usr/share/calendar/fr_FR
ln -s ru_RU.KOI8-R "$UB_INSTALLDIR"/usr/share/calendar/ru_RU
ln -s hr_HR.ISO8859-2 "$UB_INSTALLDIR"/usr/share/calendar/hr_HR
ln -s de_AT.ISO_8859-15 "$UB_INSTALLDIR"/usr/share/calendar/de_AT
ln -s hu_HU.ISO8859-2 "$UB_INSTALLDIR"/usr/share/calendar/hu_HU
ln -s uk_UA.KOI8-U "$UB_INSTALLDIR"/usr/share/calendar/uk_UA
