#!/bin/sh -eux

targets="bios efi32"
if [ $UB_ARCH="amd64" ];then
    targets="bios efi32 efi64"
fi
sed -i 's|win32/syslinux.exe||g' Makefile
export LDFLAGS+=--no-dynamic-linker
export EXTRA_CFLAGS=-fno-PIE
export UB_MAKE_PROCS=1
ub_make $targets
