#!/bin/sh -eux

# compile static lib
./configure \
	--prefix=/usr \
	--libdir=/lib
make

# compile shared lib
./configure \
	--prefix=/usr \
	--libdir=/lib \
	--shared
make

# minizip
cd contrib/minizip
autoreconf -vif
ub_compile
