diff -Naur orig/Makefile patched/Makefile
--- orig/Makefile	2016-02-05 22:22:15.000000000 +0100
+++ patched/Makefile	2016-02-28 23:38:52.648348214 +0100
@@ -26,7 +26,8 @@
 CFLAGS	= $(THREADS) $(OPT) $(W) $(XCFLAGS)
 LDLIBS	=
 SOLIBS	=
-prefix	= /usr/local
+SOVER   = 0
+prefix	= /usr
 exec_prefix = $(prefix)
 bindir = $(exec_prefix)/bin
 libdir = $(exec_prefix)/lib
@@ -38,23 +39,24 @@
 
 IHDRS	= lmdb.h
 ILIBS	= liblmdb.a liblmdb.so
+ELIBS	= liblmdb.so liblmdb.so.$(SOVER) liblmdb.so.$(SOVER).0.0
 IPROGS	= mdb_stat mdb_copy mdb_dump mdb_load
 IDOCS	= mdb_stat.1 mdb_copy.1 mdb_dump.1 mdb_load.1
 PROGS	= $(IPROGS) mtest mtest2 mtest3 mtest4 mtest5
 all:	$(ILIBS) $(PROGS)
 
-install: $(ILIBS) $(IPROGS) $(IHDRS)
+install: $(ELIBS) $(IPROGS) $(IHDRS)
 	mkdir -p $(DESTDIR)$(bindir)
 	mkdir -p $(DESTDIR)$(libdir)
 	mkdir -p $(DESTDIR)$(includedir)
 	mkdir -p $(DESTDIR)$(mandir)/man1
 	for f in $(IPROGS); do cp $$f $(DESTDIR)$(bindir); done
-	for f in $(ILIBS); do cp $$f $(DESTDIR)$(libdir); done
+	for f in $(ELIBS); do cp $$f $(DESTDIR)$(libdir); done
 	for f in $(IHDRS); do cp $$f $(DESTDIR)$(includedir); done
 	for f in $(IDOCS); do cp $$f $(DESTDIR)$(mandir)/man1; done
 
 clean:
-	rm -rf $(PROGS) *.[ao] *.[ls]o *~ testdb
+	rm -rf $(PROGS) *.[ao] *.[ls]o *.[ls]o.* *~ testdb
 
 test:	all
 	rm -rf testdb && mkdir testdb
@@ -65,7 +67,9 @@
 
 liblmdb.so:	mdb.lo midl.lo
 #	$(CC) $(LDFLAGS) -pthread -shared -Wl,-Bsymbolic -o $@ mdb.o midl.o $(SOLIBS)
-	$(CC) $(LDFLAGS) -pthread -shared -o $@ mdb.lo midl.lo $(SOLIBS)
+	$(CC) $(LDFLAGS) -fPIC -Wl,-soname,liblmdb.so.$(SOVER) -pthread -Wl,-Bsymbolic -shared -o $@.$(SOVER).0.0 mdb.lo midl.lo $(SOLIBS)
+	ln -s $@.$(SOVER).0.0 liblmdb.so.$(SOVER)
+	ln -s liblmdb.so.$(SOVER) liblmdb.so
 
 mdb_stat: mdb_stat.o liblmdb.a
 mdb_copy: mdb_copy.o liblmdb.a
