#!/bin/sh -eux

if [ $((`stat -f -c "%a" .`*`stat -f -c "%s" .`/(1024*1024*1024))) -lt 12 ]; then
	echo "At least 12 GB free space is required!"
	exit 1
fi

# átpakolunk az /ext_sources alá mindent, mert
# ott fogja keresni a letöltött forráscsomagokat
if [ ! -d ext_sources ]; then
	mkdir ext_sources
fi
# mv *.{gz,bz2,tgz,zip} ext_sources/
mv *.bz2 ext_sources/

cd main/

# fix script permissions
find . \( -name "*.sh" -o -name "*.pl" -o -name "*.py" \) -exec chmod +x {} \;

export JAVA_HOME=/usr/lib/java

export LDFLAGS="-Wl,-rpath,/usr/lib/openoffice4/program/ -Wl,--as-needed"

export CPPFLAGS="-Wno-deprecated-declarations"
export CXXFLAGS="-std=c++11"

autoconf

./configure \
	--prefix="/usr"             \
	--sysconfdir="/etc"         \
	--localstatedir="/var"      \
	--mandir="/usr/share/man"   \
	--infodir="/usr/share/info" \
	--build="i686-uhu-linux"    \
	--host="i686-uhu-linux"     \
	--with-lang="en-GB hu" \
	--with-vendor="ubk.hu" \
	--with-jdk-home="/usr/lib/java" \
	--with-ant-home="/usr/lib/apache-ant" \
	--with-system-libs \
	--with-system-headers \
	--without-system-jars \
	--without-afms \
	--without-fonts \
	--without-ppds \
	--without-junit \
	--with-system-hyphen \
	--without-system-hsqldb \
	--without-system-boost \
	--without-system-icu \
	--without-system-jpeg \
	--without-system-lucene \
	--without-system-mdds \
	--without-system-mythes \
	--disable-beanshell \
	--disable-coinmp \
	--disable-epm \
	--disable-fetch-external \
	--disable-gconf \
	--disable-gnome-vfs \
	--disable-kde4 \
	--disable-odk \
	--disable-online-update \
	--disable-pdfimport \
	--disable-saxon \
	--disable-unit-tests \
	--disable-werror \
	--enable-crashdump \
	--enable-gio \
	--enable-hunspell \
	--enable-hyphen

source ./LinuxX86Env.Set.sh
./bootstrap

cd instsetoo_native

# build --all --show -P2 -- -P2
build --all -P2 -- -P2
