#!/bin/sh -eux

if [ $((`stat -f -c "%a" .`*`stat -f -c "%s" .`/(1024*1024*1024))) -lt 12 ]; then
	echo "At least 12 GB free space is required!"
	exit 1
fi

# átpakolunk az /ext_sources alá mindent, mert
# ott fogja keresni a letöltött forráscsomagokat
mkdir ext_sources
mv *.{gz,bz2,tgz,zip} ext_sources/

cd main/

export JAVA_HOME=/usr/lib/java
export QT4DIR="/usr/lib/qt4"
export QT4INC="/usr/lib/qt4/include"
export QT4LIB="/usr/lib/qt4/lib"
export LDFLAGS="-Wl,-rpath,/usr/lib/openoffice4/program/"

autoconf

./configure \
	--prefix="/usr"             \
	--sysconfdir="/etc"         \
	--localstatedir="/var"      \
	--mandir="/usr/share/man"   \
	--infodir="/usr/share/info" \
	--build="i686-uhu-linux"    \
	--host="i686-uhu-linux"     \
	--with-lang="en-GB hu" \
	--with-vendor="ubk.hu" \
	--with-jdk-home="/usr/lib/java" \
	--with-ant-home="/usr/lib/apache-ant" \
	--with-system-libs \
	--with-system-headers \
	--without-afms \
	--without-fonts \
	--without-ppds \
	--without-junit \
	--with-system-hyphen \
	--without-system-icu \
	--without-system-jars \
	--without-system-jpeg \
	--without-system-hsqldb \
	--without-system-libwpd \
	--without-system-lucene \
	--without-system-mdds \
	--without-system-mythes \
	--disable-beanshell \
	--disable-coinmp \
	--disable-epm \
	--disable-fetch-external \
	--disable-gconf \
	--disable-gnome-vfs \
	--disable-kde4 \
	--disable-odk \
	--disable-online-update \
	--disable-pdfimport \
	--disable-saxon \
	--enable-crashdump \
	--enable-gio \
	--enable-gstreamer \
	--enable-hunspell \
	--enable-hyphen

source ./LinuxX86Env.Set.sh
./bootstrap

cd instsetoo_native

# build --all --show -P2 -- -P2
build --all -P2 -- -P2


