diff -Naur ORIG/Makefile UHU/Makefile
--- ORIG/Makefile	2013-12-09 03:51:52.000000000 +0100
+++ UHU/Makefile	2014-03-05 21:53:03.529840597 +0100
@@ -10,14 +10,14 @@
 	mkdir -p ${DESTDIR}${PREFIX}/share/anki
 	cp -av * ${DESTDIR}${PREFIX}/share/anki/
 	cd ${DESTDIR}${PREFIX}/share/anki && (\
-	mv runanki ${DESTDIR}${PREFIX}/local/bin/anki;\
+	mv runanki ${DESTDIR}${PREFIX}/bin/anki;\
 	test -d ${DESTDIR}${PREFIX}/share/pixmaps &&\
 	  mv anki.xpm anki.png ${DESTDIR}${PREFIX}/share/pixmaps/;\
 	mv anki.desktop ${DESTDIR}${PREFIX}/share/applications;\
 	mv anki.1 ${DESTDIR}${PREFIX}/share/man/man1/)
-	xdg-mime install anki.xml --novendor
-	xdg-mime default anki.desktop application/x-anki
-	xdg-mime default anki.desktop application/x-apkg
+#	xdg-mime install anki.xml --novendor
+#	xdg-mime default anki.desktop application/x-anki
+#	xdg-mime default anki.desktop application/x-apkg
 	@echo
 	@echo "Install complete."
 
