#!/bin/sh -eux

ub_install

install -Dm755 tools/qt-faststart "$UB_INSTALLDIR"/usr/bin/qt-faststart
ln -s libpostproc "$UB_INSTALLDIR"/usr/include/postproc
ln -s postproc/postprocess.h "$UB_INSTALLDIR"/usr/include/
