#!/bin/sh -eux

autoreconf -vif

ub_compile \
	--without-hal \
	--without-openal \
	--without-opencl \
	--without-oss \
	--without-capi \
	--without-tiff \
	--without-mpg123 \
	--without-sane \
	--without-netapi \
	--with-dbus
