#!/bin/sh -eux

_certdir="$UB_INSTALLDIR"/usr/share/ca-certificates/trust-source
mkdir -p $_certdir/anchors

# mozilla certificates
install -Dm644 ca-bundle.trust.crt "$_certdir"/mozilla.trust.crt
install -Dm644 ca-bundle.neutral-trust.crt "$_certdir"/mozilla.neutral-trust.crt
install -Dm644 ca-bundle.supplement.p11-kit "$_certdir"/mozilla.supplement.p11-kit

# cacert.org certificates
install -Dm644 CAcert.org_root.crt "$_certdir"/anchors/
install -Dm644 CAcert.org_class3.crt "$_certdir"/anchors/

# Trust source directories
install -d "$UB_INSTALLDIR"/{etc,usr/share}/ca-certificates/trust-source/{anchors,blacklist}

# Directories used by update-ca-trust (aka "trust extract-compat")
install -d "$UB_INSTALLDIR"/etc/{ssl/certs/java,ca-certificates/extracted}
